### ISSUE TITLE
Improve the FrontEnd Make it more Responsive

### ISSUE THREAD

**Issue by CSEdgeOff** [CSEdgeOfficial/learn.csedge.courses#1]

**Comment by Bhumika1312** [comment]
Hi @CSEdgeOff, I would like to contribute to GSSOC'24 by fixing an issue. Please assign me a problem as I have an idea to make the website responsive.

**Comment by Bhumika1312** [comment]
No, I do not have any experience this will be my first open-source contribution. I am willing to work on the home page.
And I have not done any project so far.

**Comment by shuhaki** [comment]
i would love to work on this issue.i have very good experience in fronted part, i did some good projects related to this issue so, could you please assaign it to me i will do it

**Comment by its-kumar-yash** [comment]
Hey @CSEdgeOff , I would like to work on this issue, i have prior experience in Web Development, Kindly assign this to me

**Comment by CSEdgeOff** [comment]
@its-kumar-yash @Tanishka023 @shuhaki Please specify what will work on in detail who makes a good PR first we'll merge it.

**Comment by Tejaswini-628** [comment]
Can you assign this to me? I want to work on this under GSSOC.

**Comment by Tanishka023** [comment]
> @its-kumar-yash @Tanishka023 @shuhaki Please specify what will work on in detail who makes a good PR first we'll merge it.

Can you tell me something which needs to be improved ? @CSEdgeOff

**Comment by komalgururanii** [comment]
Hey i would like to make the frontend more responsive like on the blog page

**Comment by MattipaPoojitha** [comment]
@CSEdgeOff  i would like to contribute for this issue of making more responsive and eyecatching web page.I do have previous experience in fornt end development and also my rencent contribution is similar to it.
soo kindly assign this issue to me.
Thank You!!

**Comment by CSEdgeOff** [comment]
> > @its-kumar-yash @Tanishka023 @shuhaki Please specify what will work on in detail who makes a good PR first we'll merge it.
> 
> Can you tell me something which needs to be improved ? @CSEdgeOff

The Title was right above to explain that thing.

**Comment by TheNikhilRaj** [comment]
Hii can you please assign the task to me.

**Comment by Yuvraj960** [comment]
@Durgesh-Vaigandla Please assign this issue to me under GSSoC24

**Comment by crazyshrut** [comment]
hey @MattipaPoojitha , can you assign this issue to me?
I know how to make responsive.
