### ISSUE TITLE
Home page responsiveness requires fixing

### ISSUE THREAD

**Issue by michellecordovi** [CSEdgeOfficial/learn.csedge.courses#10]
The home pages media queries could use updates on its layout, particularly for tablet sized screens. The about section becomes extremely narrow and the internships tabs become off center. 

Please assign this issue to me as I would like to contribute under GSSoC'24 . I would like to fix this issue using grid layout and additional media queries specific for tablet size screens.

**Comment by urgetolearn** [comment]
hey mentor please assign this task to me

**Comment by CSEdgeOff** [comment]
@michellecordovi could you please give more info about the bug need some screen short or recording

**Comment by michellecordovi** [comment]
@CSEdgeOff 
![CSEdge900px](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/165519977/39b985dc-765a-4e4f-9050-758ba35fa7eb)

Here is a screen shot of the CSEdge Home page at a viewport width of 900px

**Comment by CSEdgeOff** [comment]
@michellecordovi Kindly start working on this issue

**Comment by CSEdgeOff** [comment]
@michellecordovi The code files are located at folder csedge.courses 
Index.html and index.css
