### ISSUE TITLE
Centering the arrow in the go-to-top button

### ISSUE THREAD

**Issue by DNahar74** [CSEdgeOfficial/learn.csedge.courses#104]
### What's the style idea?

we need to center the arrow in the go-to-top button, and we can also reduce the overall button size.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
