### ISSUE TITLE
Docs: Adding a "Featured In" Section to the readme file which shows open source events that the project was featured in

### ISSUE THREAD

**Issue by SpaciousCoder78** [CSEdgeOfficial/learn.csedge.courses#107]
I found this on other repositories. Basically we can have a section in the readme mentioning the open source events that the project has been featured in.

Example:

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/88923986/95c5eded-3783-4096-9eda-e6f9a4e0ea10)

I would like you to assign this issue to me under Gssoc 24

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
