### ISSUE TITLE
Docs: Adding a table of contents section to the readme

### ISSUE THREAD

**Issue by SpaciousCoder78** [CSEdgeOfficial/learn.csedge.courses#108]
Adding a table of contents section to the readme file will make it easier to access the sections of the readme.

I would like you to assign this to me under gssoc 24

**Comment by vaishali-sharma-20** [comment]
Hello,
I am GSSoC'24 Contributor. I would love to contribute in this. So,  can you assign this issue to me.  I can add the table of content and also all relevant content that will help others to easily understand the Project.

**Comment by SpaciousCoder78** [comment]
@vaishali-sharma-20 We can co-author the commit if you want.

**Comment by vaishali-sharma-20** [comment]
@SpaciousCoder78  sure. Sorry for the late reply.
