### ISSUE TITLE
Enhancing User Experience with Interactive Quizzes

### ISSUE THREAD

**Issue by DeeptiWani** [CSEdgeOfficial/learn.csedge.courses#109]
### Description

We propose implementing interactive quizzes as a new feature to enhance user engagement and learning outcomes on the platform. Interactive quizzes can provide immediate feedback to users, reinforcing their understanding of the concepts covered in the courses.

**Key Functionalities:**

**Varied Question Types:** Add different question types like multiple-choice, fill-in-the-blanks, and true/false for diverse assessment.
**User-Friendly Interface:** Design a user-friendly quiz interface that is easy to navigate and interact with.
**Mobile Compatibility:** Ensure quizzes are accessible and optimized for mobile devices for on-the-go learning.

**Please assign me to this issue so that I can start working on implementing these enhancements. I'm excited to collaborate and contribute to creating a more appealing and user-friendly website.**

**Thank you for considering this proposal!**

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@DeeptiWani Are you going to make complete frontend and backend for the QUIZ Part

**Comment by DeeptiWani** [comment]
No, I won't create a complete frontend and backend for the quiz part

Interactive quizzes can provide immediate feedback to users, reinforcing their understanding of the concepts covered in the courses. This immediate feedback can be especially beneficial as it allows users to learn from their mistakes and reinforce correct answers promptly.

For example, if a user selects the wrong answer, CSEdge Learn interactive quiz feature can display the correct answer along with an explanation immediately after the question. This approach not only helps users understand why their answer was incorrect but also ensures that they grasp the correct information for future reference. 
Tech Stack-Html,CSS,JS
