### ISSUE TITLE
Contact Us section should be just above Footer Section 

### ISSUE THREAD

**Issue by imanasdash** [CSEdgeOfficial/learn.csedge.courses#11]
It will enhance website attractiveness . Please assign me this issue under Gssoc'24

**Comment by CSEdgeOff** [comment]
@imanasdash Need more details about the bug your trying to fix try to upload a screenshot or screen record of the bug.

**Comment by alishasingh06** [comment]
<img width="959" alt="Screenshot 2024-05-13 024928" src="https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/114938485/1e77d112-5863-4075-b9eb-c4d88ecb9392">

here the "Contact Us" section should be just above the footer (grey) section and the FAQ section should be above the "Contact Us" section.

@CSEdgeOff please assign me this issue so I can fix it, also please assign a level to it.
