### ISSUE TITLE
Improvise the footer section the website

### ISSUE THREAD

**Issue by MetiUmashri** [CSEdgeOfficial/learn.csedge.courses#110]
### What's the style idea?

We need to improve the footer section of the website. Could you please assign this to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
#6 Existing Issue
