### ISSUE TITLE
HOMEPAGE NAVBAR UI CAN BE IMPROVED

### ISSUE THREAD

**Issue by Nih1tGupta** [CSEdgeOfficial/learn.csedge.courses#114]
### Description

Padding and margin has to be added.
Also hover effect must be added.
its position must be fixed.

### Screenshots
![homenav'](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/119615342/c4892a62-ea6e-4912-817a-3dc0c2a3bd41)

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Nih1tGupta** [comment]
Hi there, Kindly consider this issue and please assign this to me under GSSOC'24

**Comment by alishasingh06** [comment]
@CSEdgeOff please assign me this task
