### ISSUE TITLE
Contact Page Icons Lack hover effect

### ISSUE THREAD

**Issue by Nih1tGupta** [CSEdgeOfficial/learn.csedge.courses#115]
### Description

Adding hover effect on social media icons  to make it look more beautiful

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by alishasingh06** [comment]
@CSEdgeOff please assign me this task

**Comment by Nih1tGupta** [comment]
@CSEdgeOff  ,Please consider this issue and assign it to me under GSSOC'24
