### ISSUE TITLE
CUSTOM SCROLL BAR

### ISSUE THREAD

**Issue by Nih1tGupta** [CSEdgeOfficial/learn.csedge.courses#116]
### Description

A custom scroll bar will increase user attention .

### Screenshots

![scrollbar](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/119615342/1df1338e-d1af-47f2-80c6-2f7e2a1bc4c8)
Here are some basic example .
I will work more on it once assigned.
Kindly assign this issue to me  

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [x] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
