### ISSUE TITLE
Blog page can be improvised

### ISSUE THREAD

**Issue by somaakash** [CSEdgeOfficial/learn.csedge.courses#117]
### What's the style idea?

We need to improve blog page like nav bar and ,categories and recent post.
and i would like to add more blogs in this.
can u assign this issue?

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@somaakash So many Issues are opened already regarding this work on them
