### ISSUE TITLE
Improve the pagination

### ISSUE THREAD

**Issue by jahnavithutta129** [CSEdgeOfficial/learn.csedge.courses#119]
### What's the style idea?

Can improve the pagination and home page with containers placed at a right places in a better way

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
#35 Issue is already open.
