### ISSUE TITLE
[Style]Internship Section Using BootStrap and CSS

### ISSUE THREAD

**Issue by mohitrajjha111** [CSEdgeOfficial/learn.csedge.courses#121]
### What's the style idea?

We need to improve the internship section styling.
I have an idea in mind using BootStrap and CSS

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125960660/78a3e618-c96c-41ab-8b26-b2f725a2f58f

Please see to it and assign it to me under label GSSoC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by mohitrajjha111** [comment]
Here's a PR for the same.
https://github.com/CSEdgeOfficial/learn.csedge.courses/pull/103

Please Consider Merging if possible

**Comment by shrividhii** [comment]
Hello admin I want to contribute could you please assign me this task

**Comment by vignesh-0512** [comment]
Hello @CSEdgeOff i have experienve in working on bootstrap and css so i can able to fix this issue, can you please assign me this issue under Gssoc'24.
