### ISSUE TITLE
For changing the style of Social Media Icons in Contact Us Section.

### ISSUE THREAD

**Issue by vishanurag** [CSEdgeOfficial/learn.csedge.courses#122]
### What's the style idea?

We need to change the color of the Social Media Icons present in the Contact Us section. 

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/126074487/1787a0aa-c8a2-4097-8818-507e6df917a8

I think that, the color combination of these Social Media Icons is not aligned with the overall website.
The color of these icons should be in either Black color or Light Indigo color as they fits with the overall website's UI.

- Please review my request and assign this issue to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [x] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@vishanurag What was the idea explain more and provide the screenshots of the ouput

**Comment by CSEdgeOff** [comment]
@vishanurag What was the idea explain more and provide the screenshots of the output

**Comment by vishanurag** [comment]
We can change the color of these Social Media Icons on Contact Us Section.

![github-issue-one](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/126074487/6f8e3c5f-8a7e-45e9-a8d1-f0e1485e6f6c)

We can color these icons in Black color, since the Social Media Icons of footer Section are already in white color with black background.
So, we can do these changes to make the look of the Contact Us section good.


Also, can you please add GSSOC lebels on this issue.

**Comment by vishanurag** [comment]
@Durgesh-Vaigandla Kindly assign me this issue under gssoc'24.
