### ISSUE TITLE
Update: README.md design link

### ISSUE THREAD

**Issue by AvdhutPailwan** [CSEdgeOfficial/learn.csedge.courses#125]
### Summary:
The design link of the project in the README.md is wrong

### Description:
The project design link should redirect to a design of the on figma or similar platform instead it redirects to [https://learn.csedge.courses](https://learn.csedge.courses/#!)

### Screenshots:
![Screenshot from 2024-05-12 22-51-03](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/74597375/f7aed4d7-8bbb-4bfe-89e0-728a8cbb0865)
![Screenshot from 2024-05-12 22-55-59](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/74597375/7e5b0702-6022-40f0-a528-3e970f215a8b)

**Comment by Durgesh-Vaigandla** [comment]
@AvdhutPailwan We don't have a design yet so we mention the main link.
