### ISSUE TITLE
[Feature] <write a small description here>Add a Dark Mode feature

### ISSUE THREAD

**Issue by Shivam250702** [CSEdgeOfficial/learn.csedge.courses#126]
### Description

I want to add a dark mode feature here such that it produces less strain on eyes of people who are accessing website on night

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
