### ISSUE TITLE
Adding respective icons to the navbar 

### ISSUE THREAD

**Issue by harshmishra19** [CSEdgeOfficial/learn.csedge.courses#128]
### Description

- The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.
- I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

### Screenshots

![Screenshot 2024-05-11 080754](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/115486960/901540e2-b2ba-4149-8b44-e25b7b4f65fb)
![Screenshot 2024-05-12 083752](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/115486960/307c610c-89f4-4ddc-9bd4-08ecb850251c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by brewcoder6113** [comment]
hey i can resolve this issue under gssoc'24 , Please assign the following

**Comment by vignesh-0512** [comment]
Hello @CSEdgeOff, I would like to work on this feature so can you please assign me this issue under Gssoc'24.
