### ISSUE TITLE
[Feature] <Redirection of the categories (links) to respective contents>

### ISSUE THREAD

**Issue by pand-coder** [CSEdgeOfficial/learn.csedge.courses#129]
### Description

Hello project Admin,
I would like to redirect the categories links in the blog section
 
###Screenshots

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/82692757/868e5caf-49da-4ca0-b0a6-6c11dcd57ac5)

`Doubt` : Should i redirect them to w3schools content pages or else any other content pages presnt in the website 
Please assign me this issue as i would like to work upon this 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
