### ISSUE TITLE
I can Improve the UI of Internship section as well as content of the Internship Section.

### ISSUE THREAD

**Issue by vaishali-sharma-20** [CSEdgeOfficial/learn.csedge.courses#130]
### What's the style idea?

We need to improve the Content Quality of the Internship section of all technology and also we can make it more interactive and appealing by adding hover effect. also adding different button layout.

I request you to assign this task to me so I can help you to improve it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by FatemaBaig** [comment]
Hi,
I would like to work on this part of project, please assign it to me under GSSOC-24.

**Comment by Ansh101112** [comment]
@CSEdgeOff I want to work on this issue under gssoc

**Comment by sadhvi1244** [comment]
@CSEdgeOff  I would like to work on the issue. Please assign this task to me under GSSOC'24.

**Comment by vaishali-sharma-20** [comment]
please add level at this.
