### ISSUE TITLE
Adding animation

### ISSUE THREAD

**Issue by harshmishra19** [CSEdgeOfficial/learn.csedge.courses#131]
### Description

On your Home pages' about section there is no animation added to the image used and I want to fix that by adding some animation on the image so that your page would look more appealing

### Screenshots

![Screenshot 2024-05-13 094757](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/115486960/1efb67a8-a381-485f-ae0c-dd3c4974e7dc)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
