### ISSUE TITLE
[home page navigation] <after clicking on the logo we can open the home page>

### ISSUE THREAD

**Issue by Akshatakapare** [CSEdgeOfficial/learn.csedge.courses#132]
### Description

**Issue**

When I visited the website and went to the next pages then I realized that we have to go to the previous button to go to the home page i.e. 1st page of the website, our time is wasted in doing this so have a solution.

**solution**

we can add the functionality of navigating the home page by clicking on the logo of the website, it will save time.

### Screenshots

![metaverse](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/156576791/263c6e91-ff10-4d93-98ce-e35b2570009b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@Akshatakapare This issue has been resolved already
