### ISSUE TITLE
Adding a hover effect to the social icons in the footer

### ISSUE THREAD

**Issue by varsha-saini02** [CSEdgeOfficial/learn.csedge.courses#137]
### What's the style idea?

Hello,
There is a small enchancement that I can do is that I can add a hover effect to social icons like github and linkedIn when someone clicks on thse icons. The hover effect can be that it will increase the size when someone hovers over the icon or it can change it's color also like a blur one when someone hiver over linkedin and black and white when someone hover over github etc.

So, if you find this issue relevant then please assign me this issue under GSSOC'24 . Thanks I'm awaiting for your response.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by vignesh-0512** [comment]
Hello @CSEdgeOff i have experience in css i can able to add hover effect in social media so can you assign me this task under gssoc'24.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
