### ISSUE TITLE
BUG: FAQ's image is not fixed.

### ISSUE THREAD

**Issue by HardCoder404** [CSEdgeOfficial/learn.csedge.courses#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when we click on any faq section, with that the size of the image also changed which is poor experience according to industry level.
The image should be Fixed at there own position relative to div.

Assign me this issue. I'll glad to work on that also.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vignesh-0512** [comment]
Hello @CSEdgeOff i have experience in css and bootstrap i can able to fix this issue can be fixed easily can you assign me this task under gssoc'24.
