### ISSUE TITLE
Adding  suitable icons .

### ISSUE THREAD

**Issue by Soumya6Tiwari** [CSEdgeOfficial/learn.csedge.courses#142]
### Description

Adding suitable icons for different sections in the navbar.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Soumya6Tiwari** [comment]
@Durgesh-Vaigandla  Kindly assign me this issue under gssoc'24

**Comment by sadhvi1244** [comment]
I would like to work on the issue. Please assign to me under GSSOC'24

**Comment by TheNikhilRaj** [comment]
Hii can you please assign the task to me.

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@CSEdgeOff
