### ISSUE TITLE
BUG: Social media icons are not responsive

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [CSEdgeOfficial/learn.csedge.courses#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Social media icons are not responsive
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125277258/cfaac5a8-236e-4717-a53e-c4e85ad9f44f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
@RamakrushnaBiswal Comment #10 I'll assign you in that Issue
