### ISSUE TITLE
[Style] Free Resources Section 

### ISSUE THREAD

**Issue by nisargaa20** [CSEdgeOfficial/learn.csedge.courses#146]
### What's the style idea?

We need to improve webpage by adding more resources especially the blank at the middle

Kindly assign me this issue under #gssoc'24.

![Uploading CSEdge - Resources - Google Chrome 13-05-2024 18_30_58.png…]()

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
