### ISSUE TITLE
[Style] Free Videos section

### ISSUE THREAD

**Issue by nisargaa20** [CSEdgeOfficial/learn.csedge.courses#147]
### What's the style idea?

Adding more videos at the videos section

Kindly assign me this issue under #gssoc'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by nisargaa20** [comment]
@CSEdgeOff  (Great could work on article section and videos section also. ) This message was sent by you  Thats why i created an issue separately for articles and videos section

**Comment by CSEdgeOff** [comment]
@nisargaa20 That's not a problem make PR directly.

**Comment by nisargaa20** [comment]
@ will it be considered as contribution without labels (gssoc and level) it will affect my points wright? correct me if I am wrong

**Comment by CSEdgeOff** [comment]
I'll add it before merging the PR no worries about it.

**Comment by nisargaa20** [comment]
@CSEdgeOff okay then . What about the contact us section u have not merged its not good?
