### ISSUE TITLE
[Style] The links in the blog page aren't visible

### ISSUE THREAD

**Issue by AlaynaShaheen** [CSEdgeOfficial/learn.csedge.courses#149]
### What's the style idea?

We need to improve the visibility of links in Blog footer section. As we can see that the links font color is really very light and not clearly visible. 
![Screenshot 2024-05-13 223654](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/111679498/8a9b694d-a098-417b-8e30-b08480a247ae)
Hence we can make the font of links visible by enhancing its color and size.

I am a contributor under GSSoC'24. I can resolve this issue so please assign this to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
