### ISSUE TITLE
Styling contact section

### ISSUE THREAD

**Issue by achlbatra** [CSEdgeOfficial/learn.csedge.courses#151]
### What's the style idea?

We need to improve the social media icons by adding colors and hover effects to them. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by abhinav120304** [comment]
please assign me this issue under gssoc'24
