### ISSUE TITLE
Adding hover effects on buttons

### ISSUE THREAD

**Issue by achlbatra** [CSEdgeOfficial/learn.csedge.courses#152]
### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anmollohani7** [comment]
want to work on this issue under gssoc 24

**Comment by achlbatra** [comment]
please assign me this issue under gssoc'24
