### ISSUE TITLE
[Style] UI of the navbar is not appealing

### ISSUE THREAD

**Issue by srivastav2006** [CSEdgeOfficial/learn.csedge.courses#161]
### What's the style idea?

1. Making nav bar accessible even to bottom of page and improving navbar ui
2. Using hover effects on navbar
3. About and services in navbar are not working 
 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by vansh-attri** [comment]
Hi, If anyone is not working on this issue can you please assign it to me?
