### ISSUE TITLE
[Feature] Adding Login/sign up page

### ISSUE THREAD

**Issue by vedanshipathak** [CSEdgeOfficial/learn.csedge.courses#164]
### Description

@CSEdgeOff currently the page is lacking a login/sign up page .I can create a good login/sign up page for this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@vedanshipathak Not needed for our website
