### ISSUE TITLE
[Feature] <Improve the UI of About page>

### ISSUE THREAD

**Issue by Anou25** [CSEdgeOfficial/learn.csedge.courses#165]
### Description

The About page is not so attractive, I can make it more visually appealing by providing proper color and font with appropriate image.

### Screenshots

![Screenshot 2024-05-14 221047](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/136624807/01061d24-d8ce-4261-b6f0-4439a007815c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by Rozzie-Kukal** [comment]
Hey there! Allow me to work on this under GSSOC' 2024.

**Comment by CSEdgeOff** [comment]
@Anou25 Do the necessary changes and make PR we'll check their.

**Comment by Anou25** [comment]
Ok

**Comment by Anou25** [comment]
Hi @CSEdgeOff  please can u assign it to me under GSSoC'24
