### ISSUE TITLE
Navbar lack Functionality

### ISSUE THREAD

**Issue by rahul1841** [CSEdgeOfficial/learn.csedge.courses#167]
### Description

By clicking in CSEdge icon i navbar user is not redirecting to HomePage,
Moreover i want to add dark mode buttom also which will increase user experience

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by rahul1841** [comment]
@CSEdgeOfficial please assign it to me

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024

**Comment by rahul1841** [comment]
@CSEdgeOff  please allow me to work on this issue.

**Comment by KS11177** [comment]
@CSEdgeOff  Hi, please assign this task to me , I can work on this issue in an organised manner

**Comment by CSEdgeOff** [comment]
Make PR ASAP to complete this issue

**Comment by rahul1841** [comment]
please assign this to me as i have find this,
i will do it ASAP
@CSEdgeOff

**Comment by rahul1841** [comment]
@CSEdgeOff please assign it to me
