### ISSUE TITLE
[Feature] <adding hover effect >

### ISSUE THREAD

**Issue by solanki505** [CSEdgeOfficial/learn.csedge.courses#168]
### Description

There is no hover effect to make the page more interactive I would like to add hover effect using html and css.

### Screenshots

![Screenshot 2024-05-15 173613](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/158484284/81b6ad82-e340-4bba-b7df-0a11b2a72475)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
#64 Already added Check here in the local open home.html to check
