### ISSUE TITLE
[ Fixing the Position and Improving Navbar Design ]

### ISSUE THREAD

**Issue by SAURABHVERMA00** [CSEdgeOfficial/learn.csedge.courses#176]
## Position Fixing :   
Set the navbar's position to fixed to keep it at the top of the page when scrolling.
Adjust the z-index if needed to ensure the navbar appears above other elements

## Design Enhancements : 
Add padding or margin to create space between navbar items for a clean layout.
Consider hover effects or animations for interactive elements.

please assign me solve this  thnku

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@SAURABHVERMA00 Use CSS only and make sure to check in mobile view also make clear comments what you changed and while making PR add images of o/p also in different views

**Comment by SAURABHVERMA00** [comment]
ok thanku

**Comment by CSEdgeOff** [comment]
@SAURABHVERMA00 @souravgope This is an Open source project anyone can work and make PR's the one who make an efficient code and cool UI. That will be selected for merging while merging we'll add the labels

**Comment by Siddhi561** [comment]
hey, can you assign me this issue if issue is still not solved? This is my first time in open source and I really want to showcase my skills.
