### ISSUE TITLE
 Update Footer Year Dynamically in About Page

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [CSEdgeOfficial/learn.csedge.courses#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @CSEdgeOff . I noticed that the footer year in about page on our website is static and needs to be updated manually. To improve user experience and ensure the footer always displays the current year, I propose implementing a dynamic update mechanism. In short, the copyright year is hardcoded in about.html, resources.html, internship.html and in some other html files and I want to make it dynamic.

**Please assign the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
@SaiTejaswaniBikkasani Make changes in all HTML Pages also and make PR ASAP.
