### ISSUE TITLE
BUG:Fixing the footer

### ISSUE THREAD

**Issue by YadlaMani** [CSEdgeOfficial/learn.csedge.courses#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

footer in this url https://learn.csedge.courses/
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/133841094/876626e2-b2e5-4055-b8b9-bcb63595c47e)
footer in this url https://csedge.courses/
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/133841094/78db056b-ffe9-4c44-9636-6dba785b9c6d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by YadlaMani** [comment]
@CSEdgeOff pls assign me this issue under gssoc'24

**Comment by CSEdgeOff** [comment]
@YadlaMani This is an existing issues if you really want to contribute make PR we'll add the label their.

**Comment by YadlaMani** [comment]
@CSEdgeOff do assing me that issue if possible
