### ISSUE TITLE
Internship cards

### ISSUE THREAD

**Issue by riddhi5474** [CSEdgeOfficial/learn.csedge.courses#181]
### What's the style idea?

![Screenshot_16-5-2024_165651_csedge courses](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/129864881/f7b6b66a-7a64-426d-832c-25953fc66041)

## Improvements proposed:
- Enhance the overall appearance of this section to achieve a more professional look.
- Consider making the heading bold for emphasis.
- Address the alignment of the cards, particularly in the last row, as it currently detracts from visual appeal.

I hope that you assign this work to me under GSSoC'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@riddhi5474 Make the PR ASAP

**Comment by Siddhi561** [comment]
hey, can you assign me this issue if issue is still not solved? This is my first time in open source and I really want to showcase my skills.
