### ISSUE TITLE
Change footer style, It can be enhanced more.

### ISSUE THREAD

**Issue by jain-anshika** [CSEdgeOfficial/learn.csedge.courses#182]
### What's the style idea?

We need to improve footer as it is very messy and not looking professional at all. 
Please assign this issue to me under GSSoC'24. 
I will not disappoint you and would like to work on this issue.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@jain-anshika Make PR ASAP

**Comment by YadlaMani** [comment]
@CSEdgeOff can you assign me this issue

**Comment by yogita-github** [comment]
@jain-anshika 
I would like to work on this issue can you please assign it to me.
