### ISSUE TITLE
[Technical Writing] Write an Article on complete Java AWT in the website

### ISSUE THREAD

**Issue by CSEdgeOff** [CSEdgeOfficial/learn.csedge.courses#183]
### Description

# [Technical Writing] Write an Article on complete Java AWT in the website

- Go to the Directory posts create a Java folder if exists work inside that
- Create a file that need to be consists an article on Java AWT completely almost either make 3 files by dividing the content into 3 levels Basic to advanced 
-  Use images and code snippets.
- Add any new ideas if you're willing to do in that article.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Suraj-kumar00** [comment]
Hi @CSEdgeOff, I am Suraj, and I write the technical blog at [Hashnode](https://surajk00.hashnode.dev/). 
I would like to work on this issue as I have experience in technical writing and If I need some extra details while writing I'll contact you.
Please assign it to me so that I can work on this under the GSSOC'24 contributor

**Comment by Karthikkariappa08** [comment]
Hi @CSEdgeOff  ,
I'm excited to tackle the task  With my experience in website development .

Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!

**Comment by TheNikhilRaj** [comment]
Hello @CSEdgeOff ,
Please assign this task to me.

**Comment by Ananya-Nair20** [comment]
Hello @CSEdgeOff 

I am participating in GSSOC'24. I would like to write a detailed article on Java AWT for your project. Could you please assign this task to me?

Thank you

**Comment by Ananya-Nair20** [comment]
Thank you @CSEdgeOff for assigning this issue to me. I am currently working on it.

**Comment by vaishali-sharma-20** [comment]
Hello @CSEdgeOff ,
I would really like to contribute to this part of the project. Please assign this to me also. I will try my best to provide you with the best content of Java AWT.
