### ISSUE TITLE
Improve the UI of apply button

### ISSUE THREAD

**Issue by souravgope** [CSEdgeOfficial/learn.csedge.courses#186]
### What's the style idea?

i will improve the ui of apply button using margin padding and additionally i will give the hover effect to that button
![Screenshot (173)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/137763197/6ccaa6d8-c0f5-4fab-9157-1fbfa34fe5ba)
please assgin me and give the level of gssoc @CSEdgeOff 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by souravgope** [comment]
thank you @Durgesh-Vaigandla  i already create a pull request please accept it

**Comment by Siddhi561** [comment]
hey, can you assign me this issue if issue is still not solved? This is my first time in open source and I really want to showcase my skills.

**Comment by souravgope** [comment]
hey @Durgesh-Vaigandla finally i done it please accept the Prs
 
![Screenshot (177)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/137763197/df420a52-4df9-4166-a682-cace626dfc98)

2nd image is hover effect of apply button
![Screenshot (178)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/137763197/c8b98217-8cdd-42ec-a039-4eead7dcb769)
