### ISSUE TITLE
Adding a contact us section in the footer section 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [CSEdgeOfficial/learn.csedge.courses#188]
### Description

Adding a contact us section in the footer section that will consist of social media links ie GitHub, twitter, Facebook, LinkedIn,Instagram . This would enhance the website contact .

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by NAVYA260** [comment]
I am interested in addressing this issue and would like to be assigned to make the necessary changes.
