### ISSUE TITLE
Styling and alignment of the blogs of the website

### ISSUE THREAD

**Issue by KeerthiVuppala24** [CSEdgeOfficial/learn.csedge.courses#189]
### What's the style idea?

We need to improve alignment and enhancing the styling of the blogs, Add a bit animation to the blogs, adding internship and other missing tabs even on home screen. Addition of favicons to other pages, making the website responsive as per different layouts.
I am willing to work on these issues I hope these can be assigned to me @CSEdgeOff 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by jahnaviyallamelli** [comment]
i would like to solve this issue as a GSSOC'24 contributor please assign this task to me
