### ISSUE TITLE
[ENHANCEMENT] Dark Mode

### ISSUE THREAD

**Issue by chaitanyarora** [CSEdgeOfficial/learn.csedge.courses#19]
Will develop a dark mode face of the website

**Comment by chaitanyarora** [comment]
Can you please assign me this issue?

**Comment by Abhiramofficial01** [comment]
@CSEdgeOff I would love to contribute my skills in this project which I already experienced , can you please assign this task to me for my GSSOC tag?

**Comment by CSEdgeOff** [comment]
@chaitanyarora Are you really willing to work on this issue

**Comment by Abhiramofficial01** [comment]
I am willing to work on this issue @CSEdgeOff ,kindly assign this task ..

**Comment by chaitanyarora** [comment]
@CSEdgeOff Absolutely sir!

**Comment by chaitanyarora** [comment]
#140

**Comment by chaitanyarora** [comment]
#140

**Comment by sancharigandhi** [comment]
I am willing to add moon and sun icons for toggling between dark and light modes. @CSEdgeOff, could you please assign this issue to me?

**Comment by TheNikhilRaj** [comment]
Hii can you please assign the task to me.
@CSEdgeOff

**Comment by Yuvraj960** [comment]
@Durgesh-Vaigandla Please assign this issue to me under GSSoC24. I will develop this very efficiently
