### ISSUE TITLE
[Feature] Adding hover effect in footer

### ISSUE THREAD

**Issue by 1911aditi** [CSEdgeOfficial/learn.csedge.courses#190]
### Description

Hi
i saw there is no hover effect in the footer. Can i add?
also i want to contribute in GSSoC24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by satyendushukla** [comment]
Assign it to me,i will surely do it and fix that issue soon

**Comment by sakeel-103** [comment]
The social media icons in the footer section lack a hover style.
Please assign me this issue I'll add hover style in the footer social media icons .
I will love to work on this issue if you will assign me to.

@CSEdgeOff assign me this issue under GSSoC'24.

**Comment by Adiaparmar** [comment]
Hi i would like to work on this issue. can you assign it to me?

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @CSEdgeOfficial under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.
