### ISSUE TITLE
BUG: Grammatical error in FAQ

### ISSUE THREAD

**Issue by Ajita369** [CSEdgeOfficial/learn.csedge.courses#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Except for the first FAQ answer all other FAQ answers have every first letter capital for every word which is not grammatically correct.
Here are few screenshots : 
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/162597493/4fa889d0-1f56-4501-b6db-a443acd7f742)
 
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/162597493/37115a1d-ce89-4e09-8b95-034d0866fcbe)
I will like to work on this issue so please assign this issue to me under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
@Ajita369 Make your PR

**Comment by iemafzalhassan** [comment]
## Hey Folks
Is Anyone working on this issue ?
