### ISSUE TITLE
Make the search bar works efficiently 

### ISSUE THREAD

**Issue by CSEdgeOff** [CSEdgeOfficial/learn.csedge.courses#2]

**Comment by Suraj-kumar00** [comment]
Hi @CSEdgeOff, how are you doing?
I under the issue and willing to work on it under the GSSoC'24 program and I'm familiar in working with HTML, CSS(Bootstrap and tailwindcss), JavaScript which the project requires.
Can you please assign this issue to me so that I can work on it?

**Comment by Suraj-kumar00** [comment]
HI @Durgesh-Vaigandla @CSEdgeOff, Thanks for assigning this to me. I'll report you shortly about the progress of the porject.

**Comment by sadhvi1244** [comment]
I'd like to address the matter. Kindly assign this task to me for GSSOC'24.

**Comment by Raghavi-22** [comment]
As a contributor of GSSOC'24,I would like to work on this issue.I have implemented search functionality in my previous work.
MY previous project **[GITHUB](https://github.com/Raghavi-22/grp-8_22074021)**.With my prior experience I would like to contribute to this project.
Could you assign me this issue for GSSOC'24.
