### ISSUE TITLE
Regrading website Animations

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [CSEdgeOfficial/learn.csedge.courses#20]
Hi i am ram,
#gssoc24
i can add animations in your website which looks more attractive.
tech stack to be used:-
-aos.js(for scrolling effect)
-darkmode.js(for dark mode)
-tilt.js
-ityped.js

**Comment by RamakrushnaBiswal** [comment]
Hi @CSEdgeOff  sir this one is the landing page https://csedge.courses/#contact

**Comment by CSEdgeOff** [comment]
@RamakrushnaBiswal Yes that is the main Domain and for the blog learn.csedge.course

the main Domain code files are located in the folder named csedge.courses.

**Comment by Akshatakapare** [comment]
I would like to contribute to this issue. Could you please consider assigning this issue to me? I'm committed to dedicating my time and effort to delivering a high-quality design that aligns with the project's goals.

Looking forward to the opportunity to work on this exciting project!

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@CSEdgeOff

**Comment by RekhaKushwaha01** [comment]
I would like to work on this project. Please assign me this issue under GSSOC'2024
