### ISSUE TITLE
[Feature] : Add Social media icons in footer section

### ISSUE THREAD

**Issue by Saimanjari777** [CSEdgeOfficial/learn.csedge.courses#200]
### Description

Adding twitter, Instagram and Facebook social media icons at the footer section.
Please assign this issue to me @CSEdgeOff 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by sakeel-103** [comment]
The social media icons in the footer section lack a hover style.
Please assign me this issue I'll add hover style in the footer social media icons .
@CSEdgeOff  assign me this issue under GSSoC'24.

**Comment by Daksh-khandelwal-1495** [comment]
Hi there @CSEdgeOff ! 
Have good experience in front-end development. 
Would be great to get to fix this issue and the requested icons on the page in a good format. 

Looking forward to be assigned to the issue for the same

**Comment by JanitKumar** [comment]
i can fix this issue assign it to me
