### ISSUE TITLE
BUG: Cant see the whole dropdown on about page.

### ISSUE THREAD

**Issue by kdanjana** [CSEdgeOfficial/learn.csedge.courses#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When you open the page on mobile, we cant see the whole dropdown.
<img width="368" alt="before" src="https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/103878831/15e80158-59b9-40bc-8876-7b835ecd3cd4">
I would like to add scroll bar and highlight the buttons - Home, About, Contact buttons when cursor hovers over them.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by atharvarekhawar** [comment]
hey @CSEdgeOff , I would like to contribute to the issue , I t has been 2 weeks and no response so if no one is working on it then please assign it to me.
