### ISSUE TITLE
[Style] Parallax effect on internship cards

### ISSUE THREAD

**Issue by Ridhima10** [CSEdgeOfficial/learn.csedge.courses#205]
### What's the style idea?

I would like to add a parallax effect on Internship cards.
The cards will look more realistic
Like this:
https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/85826117/17dd92fb-86c2-4bbe-91ce-93f927cedf50

Kindly assign me this issue.
Best regards

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by souravgope** [comment]
hey @CSEdgeOff  i want to work on this issue

**Comment by Ridhima10** [comment]
@CSEdgeOff kindly view my PR. I have resolved your issue .It has been a week

**Comment by Ridhima10** [comment]
@CSEdgeOff  Check it now please
