### ISSUE TITLE
[hover style] The social media icons in the footer section lack a hover style.

### ISSUE THREAD

**Issue by sakeel-103** [CSEdgeOfficial/learn.csedge.courses#206]
### What's the style idea?

The social media icons in the footer section lack a hover style.
Please assign me this issue, I will add this style to footer section social media icons .
@CSEdgeOff  please assign me this issue under GSSoC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by mrunal1309** [comment]
@Durgesh-Vaigandla Can you please assign me this issue?
