### ISSUE TITLE
[Technical Writing] Setting Up a Local GitHub Repository Blog Post on website

### ISSUE THREAD

**Issue by Rupa-Rd** [CSEdgeOfficial/learn.csedge.courses#207]
### Description

The CSEdge-Learn website contains all the beginner blog tutorials that will help the naive contributors to open source. Since, most of the development will be on the local machine, I would like to add a blog post on 'Setting Up a Local GitHub Repository' on the CSEdge-Learn website (https://learn.csedge.courses/) to guide the new contributors in setting up their own local github repository.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Durgesh-Vaigandla** [comment]
@Rupa-Rd make your PR ASAP after verification we'll assign the level

**Comment by Rupa-Rd** [comment]
> @Rupa-Rd make your PR ASAP after verification we'll assign the level

Sure, I'll make a PR by end of the day,
