### ISSUE TITLE
[Technical Writing] Write a detailed article on how to create a REST API using Node JS and Mango DB and how to host it.

### ISSUE THREAD

**Issue by Durgesh-Vaigandla** [CSEdgeOfficial/learn.csedge.courses#209]
### Description

Write a detailed article on how to create a REST API using Node JS and Mango DB and how to host it.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Rupa-Rd** [comment]
@Durgesh-Vaigandla , I would like to work on this!
Kindly assign this issue to me.

**Comment by Durgesh-Vaigandla** [comment]
@Rupa-Rd We need a perfect article that won't raise any errors to our interns make it well

**Comment by Rupa-Rd** [comment]
> @Rupa-Rd We need a perfect article that won't raise any errors to our interns make it well

Since, I've my exams. I would like to take 2 days of time to complete this. 
I'll ensure my blog instructions for the interns are error-free. I'll test them on my local machine before creating a pull request.
