### ISSUE TITLE
Search section

### ISSUE THREAD

**Issue by kdanjana** [CSEdgeOfficial/learn.csedge.courses#21]
Hi , the search section can be enhanced by giving gap between search box, button and "no matching documents found".

**Comment by nisargaa20** [comment]
Please assign me this issue #gssoc24

**Comment by CSEdgeOff** [comment]
Please specify the bug in detail.

**Comment by kdanjana** [comment]
When the error "No matching documents found." is displayed,  it is displaying at the start of the box 
<img width="291" alt="sthg1" src="https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/103878831/1bad0268-43b3-446a-9996-a39c91097dcc">
we can display it at the center like this, 
<img width="286" alt="sthg2" src="https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/103878831/0c9c5c46-98ed-47a4-84ad-5e5f83673390">

**Comment by neeleshkr22** [comment]
Please assign me this issue #gssoc24

**Comment by CSEdgeOff** [comment]
@kdanjana Sorry to say this the functionality was added already update your repo.

**Comment by Ankit389** [comment]
Please assign me this issue #21
