### ISSUE TITLE
BUG: Issue in UI

### ISSUE THREAD

**Issue by prasukjain07** [CSEdgeOfficial/learn.csedge.courses#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Home page is not properly responsive

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/115997785/d14ef91d-8b6c-4497-bdff-37c29c711b0e)

please assign this issue to me under GSSoC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by prasukjain07** [comment]
Please check the PR

**Comment by naisargi17** [comment]
I want to work on this issue .
