### ISSUE TITLE
[Feature] Add a Pre-Loader 

### ISSUE THREAD

**Issue by Durgesh-Vaigandla** [CSEdgeOfficial/learn.csedge.courses#216]
### Description

# Add a pre-loader for every page 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by mtg718** [comment]
hi, @CSEdgeOff ,I would like to contribute it under GSSoC'24.

**Comment by mtg718** [comment]
Hi @Durgesh-Vaigandla, upto how much time I can complete this?

**Comment by mtg718** [comment]
Hi @ Durgesh-Vaigandla, I am working on another one please assign it to someone else, thank you.

**Comment by sakshi261203** [comment]
Hi Durgesh-Vaigandla, Could you please assign me this issue??
