### ISSUE TITLE
Add Social Media  And Feedback Section In Blog Page

### ISSUE THREAD

**Issue by yashbalpande** [CSEdgeOfficial/learn.csedge.courses#22]
Please assign this task to me, 
I'll work on adding exciting features like a dark mode to the blog pages. Readers often enjoy reading content in dark mode, so incorporating this feature can enhance their experience on the website. Additionally, I'll integrate social media sections to encourage users to follow CSEdgeOfficial on various platforms. By increasing our social media presence, we can attract more members and foster greater engagement with our audience 
Assign me this issue under GSSoC 24.

**Comment by Karthikeyan1508** [comment]
I would like to be assigned this task.

I am looking forward to improving our blog pages to provide a better reading experience to our users and increase interaction. The primary enhancement I intend to make is to introduce a dark mode function which accommodates a darker screen for individuals who prefer this option. This will help improve the rate of reading and reduce eye strain. I also intend to incorporate various social media sections throughout the site where our users can follow us at CSEdgeOfficial on platforms such as Twitter, Facebook, and Instagram to promote a sense of community in which users are constantly up to date about the latest content, events and other announcements. Through these design improvements, I hope not only to satisfy the expectations of our regular users but also to welcome more users, which are important to our growth and future evolution.

**Comment by AmrutaJayanti** [comment]
@CSEdgeOff can you assign this task to me . I would to work for this project under GSSOC'2024

**Comment by RekhaKushwaha01** [comment]
I would like to work on this project. Please assign me this issue under GSSOC'2024
