### ISSUE TITLE
Add hover of header text is CSEdge learn 

### ISSUE THREAD

**Issue by Rauukr** [CSEdgeOfficial/learn.csedge.courses#221]
### What's the style idea?

Add hover of header text is CSEdge learn  please assign me as  GSSOC'24 contribution

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Rauukr** [comment]
please assign me as GSSOC'24 contribution

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @CSEdgeOfficial under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.
