### ISSUE TITLE
Internship page is not responsive & UI is aligned as well

### ISSUE THREAD

**Issue by GarimaSingh0109** [CSEdgeOfficial/learn.csedge.courses#23]
The internship cards are not aligned in the page. they need to be aligned to the center & make them responsive as well

**Comment by GarimaSingh0109** [comment]
i am willing to improve the UI and make the page responsive. Kindly assign me the issue under #18 #gssoc'24

**Comment by CSEdgeOff** [comment]
You're talking about complete different website which is a main one we're setup this project only which is on learn.csedge.courses

Contributors need to work on - learn.csedge.courses
not on csedge.courses

Make sure your contributions are on learn.csedge.course
But if you're really wanted to contribute for that we'll take that and further, I'll explain the procedure.

**Comment by GarimaSingh0109** [comment]
I am willing to work on that  issue kindly explain me the procedure & guide me further

**Comment by CSEdgeOff** [comment]
@GarimaSingh0109 Text here 7995665539 and send the screenshots of the issue and which enhancements you're willing to work on.
