### ISSUE TITLE
change in footer

### ISSUE THREAD

**Issue by uppercircuit** [CSEdgeOfficial/learn.csedge.courses#231]
### What's the style idea?

footer design is not up to the mark there is allot of unwanted space below the footer section please assign me issue under the gssoc 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by vermagithubcs** [comment]
@CSEdgeOff, I am interested in changing the footer. Please assign me to work on this issue!
