### ISSUE TITLE
[Feature] Add Hover Effect in Navbar

### ISSUE THREAD

**Issue by jency1** [CSEdgeOfficial/learn.csedge.courses#239]
### Description

Currently, the navbar does not have any hover effect for its items, which makes it less interactive and less visually appealing. Adding a hover effect would enhance the user experience by providing visual feedback when users navigate through the menu items.

I will implement a hover effect for the navbar items to improve interactivity and usability.

I'm a GSSOC'24 Contributor.

Please assign this issue to me so I can implement the necessary changes. 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @CSEdgeOfficial under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.
