### ISSUE TITLE
[Feature] Add Hover Effect on Links in Footer Section

### ISSUE THREAD

**Issue by jency1** [CSEdgeOfficial/learn.csedge.courses#240]
### Description

The links in the footer section currently do not have a hover effect, which makes them less interactive and visually engaging. Adding a hover effect will enhance the user experience by providing visual feedback when users interact with these links.

Please assign this issue to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @CSEdgeOfficial under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.
