### ISSUE TITLE
[Style] BLOG PAGE

### ISSUE THREAD

**Issue by AshishKumarSamantaray** [CSEdgeOfficial/learn.csedge.courses#246]
### What's the style idea?

We need to improve the overall UI UX of the blog page. It looks completely scattered and vague. Being a UI UX designer and being a graphic designer, I have a experience of designing the websites. Kiindly allow me to work over this . The required the changes are shown below through drawn wireframes over the exisiting website screenshot. Further there is a huge spacing error in the nav bar.

![Screenshot 2024-05-20 203640](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/121350516/57515dc7-dc61-4cb5-8251-ae4f58a5cc30)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Durgesh-Vaigandla** [comment]
@AshishKumarSamantaray kindly start working on our project we'll assign the level later based on the output.

**Comment by AshishKumarSamantaray** [comment]
I have already started working on it sir
