### ISSUE TITLE
Free Content Page UI

### ISSUE THREAD

**Issue by Japneet001** [CSEdgeOfficial/learn.csedge.courses#25]
**Is your feature request related to a problem? Please describe.**
Users are finding it difficult to navigate and access free content on the website due to the current layout and user interface.

**Describe the solution you'd like**
I would like to see a redesign of the free content page UI to make it more user-friendly and intuitive. This could include organizing content into categories, improving search functionality, and providing clear navigation paths.

**Comment by CSEdgeOff** [comment]
You're talking about complete different website which is a main one we're setup this project only which is on learn.csedge.courses

**Comment by Japneet001** [comment]
learn.csedge.courses have only one page (Blog). If I am wrong pls rectify me. 

And I really want to contribute to this project. Could you pls tell me the procedure

**Comment by CSEdgeOff** [comment]
@Japneet001 you mentioned free content page that was located in main domain csedge.courses 
This project is on sub domain learn.csedge.courses 
please specify the link which page your willing to work on

**Comment by Japneet001** [comment]
@CSEdgeOff I am willing to work on https://csedge.courses/Resources.html

But could you pls specify the links that are a part of learn.csedge.courses, so that I can contribute to that sub-domain

**Comment by Japneet001** [comment]
Please add Level also of the issue

**Comment by Japneet001** [comment]
@CSEdgeOff Please add Level also of this issue and assign this issue to me.
