### ISSUE TITLE
[Feature] spacing required between header and blog body content 

### ISSUE THREAD

**Issue by kapilG0** [CSEdgeOfficial/learn.csedge.courses#252]
### Description

Spacing is required between header and blog content 
![Screenshot_20240521_124153](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/59639410/61650cb0-4073-41ab-81db-8172e502dc82)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by kapilG0** [comment]
Hello @CSEdgeOff please assign this issue to me under gssoc 24

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @CSEdgeOff  under GSSoC'24. It would be a pleasure for me to work in this issue. Kindly assign this issue to me.
