### ISSUE TITLE
[Style] Moving Search bar to the top in mobile view

### ISSUE THREAD

**Issue by AMISH-KHAN** [CSEdgeOfficial/learn.csedge.courses#253]
### What's the style idea?

We need to move search bar to the top as it will be efficient for the user'

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/123164129/2c31dfc0-79e0-43b5-a38d-2f8cbe8a6534)

please assign this issue to me under GSSOC

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by sharmilapadhy23** [comment]
I would like to work on this project.Please assign me
