### ISSUE TITLE
Adding hover effect to E-book card

### ISSUE THREAD

**Issue by root-0101** [CSEdgeOfficial/learn.csedge.courses#255]
- It would be great if we add the hover effect to the cars as it improves the user experience and interaction with the content of the page.

![Screenshot 2024-05-22 040418](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/142779809/e77a2433-07b7-4f3e-9385-bc4779665a6d)

**Comment by PoojaGadagi08** [comment]
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.
