### ISSUE TITLE
Navbar items are not equally distanced [Style]

### ISSUE THREAD

**Issue by Rupalpy** [CSEdgeOfficial/learn.csedge.courses#256]
### What's the style idea?

We need to improve the navbar of the home page , the items are not equally spaced to each other .
![Screenshot_20240522_094355](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/121295967/16e9b820-5c0d-4386-9657-3b1641e84549)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@Rupalpy Fix it ASAP
