### ISSUE TITLE
[Feature]:  adding hovering effect to internships section

### ISSUE THREAD

**Issue by reshamsai150** [CSEdgeOfficial/learn.csedge.courses#257]
### Description

In the internship section cards are static  adding a hovering effect to them could change the user experience 
I am looking forward to contributing to this issue @CSEdgeOff 

### Screenshots

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/164533685/fdec9355-9075-4c7e-92b2-a731b051e93c)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by HimangshuRanjan** [comment]
@CSEdgeOff, I would like to fix this issue. Please do assign me this under GSSOC'24.
