### ISSUE TITLE
[Feature]: Add AI internship

### ISSUE THREAD

**Issue by Saimanjari777** [CSEdgeOfficial/learn.csedge.courses#263]
### Description

I want to add the Artificial Intelligence Internship under the internships section.
I want to work on this issue.
Please assign this task to me @C

### Screenshots

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/130165687/c0bb4239-136e-4609-998b-21c5a65757ea)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@Saimanjari777 we're not providing that internship if you're willing to create a good curriculum along with that you can work on this
