### ISSUE TITLE
BUG: Changes in Heading for better look

### ISSUE THREAD

**Issue by Ankur-Rai-19** [CSEdgeOfficial/learn.csedge.courses#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Require changes in the heading for the better look and feel 

"It needs some padding in the heading to fill the gap from the navigation bar."

![CSEdge-Learn-Unlocking-Interns- Prob](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125396300/e5ad8cd6-d001-43f5-98f1-50ea19bc27a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakshampurohitt** [comment]
pls let me do it under gssoc 24

**Comment by ahuja05** [comment]
Please assign me this issue. I would change the fonts and make it look attractive
