### ISSUE TITLE
BUG:# Navbar Padding and Alignment Issues

### ISSUE THREAD

**Issue by driyash9881** [CSEdgeOfficial/learn.csedge.courses#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Problem Description

In the navbar of the webpage, there is no padding and the elements are not properly aligned. This issue affects the usability and visual appeal of the navbar, making it look cluttered and unorganized.
## Expected Behavior

The navbar should have adequate padding around its elements, and the elements should be properly aligned to provide a clean, organized, and visually appealing navigation bar.

## Actual Behavior

The navbar lacks adequate padding and the elements are misaligned, resulting in a cluttered and unorganized appearance.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
#259
