### ISSUE TITLE
RealTime Tech updates section using web scraping

### ISSUE THREAD

**Issue by Sushanth-Hebri** [CSEdgeOfficial/learn.csedge.courses#27]
hey @CSEdgeOff , I would like to contribute on a new section "**Realtime tech news updates** " by using web scraping technology .
Readers often interested in current news on technology and gadgets mainly students, so if we add one section in blog page it will be more interactive and dynamic .

Can you please assign this task to me. 
Regards 
Sushanth Hebri

**Comment by CSEdgeOff** [comment]
Currently this is static website how would you implement this in the static webpages.

**Comment by Sushanth-Hebri** [comment]
Ok , its possible if we have servers.
