### ISSUE TITLE
BUG: Alignment problem in Header

### ISSUE THREAD

**Issue by Bhavishya2601** [CSEdgeOfficial/learn.csedge.courses#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a header problem in webpage, the spacing between each of them is uneven, I wanna make it correct
![Screenshot 2024-05-23 224835](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/147748752/9aadde5d-ff33-47f7-b32c-b43dbab27f9f)

Please assign this task to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HimangshuRanjan** [comment]
I would like to fix this issue. Please do assign me this under GSSOC'24.
