### ISSUE TITLE
BUG: Require changes in Footer

### ISSUE THREAD

**Issue by Ankur-Rai-19** [CSEdgeOfficial/learn.csedge.courses#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Require changes in the footer section. Remove underlines from links in the footer for better website appearance.

Screenshot:
![CSEdge-Learn-Unlocking-Interns-prob-footer](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125396300/1e0c4d8f-3389-445d-b55d-f5f72e185e8f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vaishali-sharma-20** [comment]
Hello @CSEdgeOff , I would like to help you with this footer section. I can improve its appearance. Please assign this to me.

**Comment by sakshampurohitt** [comment]
pls assign me under gssoc 24

**Comment by vaishali-sharma-20** [comment]
#296

**Comment by vaishali-sharma-20** [comment]
#296 dk
