### ISSUE TITLE
[Feature] <Adding home page link on website name on the top left.>

### ISSUE THREAD

**Issue by AdityaRaj150** [CSEdgeOfficial/learn.csedge.courses#28]
### The website name (CSEdge Learn) on the top left is a plain text and clicking on it doesn't redirects to the home page.
If a user goes a sub link (let's say how to create account in microsoft azure article of the blog), to go back to the home page, user have to click on the back button of the browser **which leads to a bad user experience.**

**solution**
By redirecting to the home page by adding home-page link to the main title will solve the problem.
**please assign me this issue  under #gssoc'24**

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Tanishka023** [comment]
Heyy!! Can you please assign this to me, I'm eager to contribute and would love working on this under GSSoC'24.
Thanks!
