### ISSUE TITLE
[Style]: Navbar and Main Heading should have some gap 

### ISSUE THREAD

**Issue by shreya-paul-17** [CSEdgeOfficial/learn.csedge.courses#281]
### What's the style idea?

We need to have some space between the navbar and Main Heading(i.e. The Welcome Heading) of this project. It will look good and will enable better enhancement of the page. 

Here is an attached screenshot of the same:
![csedge-2](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/135226069/232023c6-6797-4b78-a889-a7ce64b0b5ae)

Could you please assign this task to me ? I would like to work on this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Kavita1928** [comment]
@shreya-paul-17 I want to work for this task
