### ISSUE TITLE
[Style]: Proper alignment of the <a> tags in the footer section

### ISSUE THREAD

**Issue by shreya-paul-17** [CSEdgeOfficial/learn.csedge.courses#282]
### What's the style idea?

We need to improve the alignment of the anchor tags in the footer section. If it aligned to the left then it will look more neat and organized.

Here is an attached screenshot of the current situation:
![csedge-3](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/135226069/c36fdebc-c49d-4c8c-89cf-74e4f79fa3b8)

Could you please assign this task to me? I would like to work on this.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Kavita1928** [comment]
@shreya-paul-17 I want to work on this project
