### ISSUE TITLE
[Style] Internship page improvement

### ISSUE THREAD

**Issue by archa8** [CSEdgeOfficial/learn.csedge.courses#287]
### What's the style idea?

Need to improve the feel of the Internship page, especially fonts and colour scheme used.
![Screenshot 2024-05-24 172553](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/128168561/b914aeb8-7922-45b1-9489-e7b42a87d6f2)

Kindly assign me this issue under GSSoC'24.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by saiumasankar** [comment]
I am gssoc'24 contributor and I follow Contributing guidelines. Please assign this issue to me

**Comment by numitasahu** [comment]
Hii CSEdgeOff
The internship , free content and blog page is looking very simple I want to make it more attractive by adding hover effects
Can you please assign this task to me under gssoc24
 please assign me this issue , resolving it would increase attractiveness and look good.
