### ISSUE TITLE
[Style]

### ISSUE THREAD

**Issue by rajlaxmi03** [CSEdgeOfficial/learn.csedge.courses#29]
### What's the style idea?

We need to improve

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by rajlaxmi03** [comment]
The style needs to be improved and I can make it animated and responsive

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.
