### ISSUE TITLE
[Style] full screen internship section leaves more space in between 

### ISSUE THREAD

**Issue by AdhithiManjunath** [CSEdgeOfficial/learn.csedge.courses#293]
### What's the style idea?

We need to improve this alignment issue that is found when screen is of 100% width , it has to be interactive and spacing should be as the required one in this case . I even thought of making changes in its ui to enhance this area  and add featues.
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/130202961/57f829e4-8a40-42e1-95ab-3c2a633737f8)
please allocate me this issue so that i can contribute 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by newcodergit** [comment]
Please assign me this issue.
