### ISSUE TITLE
button orientation in resources area 

### ISSUE THREAD

**Issue by AdhithiManjunath** [CSEdgeOfficial/learn.csedge.courses#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/130202961/da72f92b-9938-4ded-aa29-c88d4e064f99)
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/130202961/1421dee3-bd58-443f-8c40-576f6fdedfce)

the buttons are irregularly places which is not highlighting or enhancing the overall UI , would want to contribute and make changes , please do allocate me this issue so that i can contribute 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Yashmishra06** [comment]
please assign me the issue under Gssoc 2024

**Comment by CSEdgeOff** [comment]
@AdhithiManjunath Work in the resources.html file only don't make changes in other files and make sure you fetch the repo before working to update new commits
