### ISSUE TITLE
BUG: Contact Section duplicacy

### ISSUE THREAD

**Issue by vaishali-sharma-20** [CSEdgeOfficial/learn.csedge.courses#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

You have given the contact section at 2 places on the same page i.e at Contact Us section and Footer, which is irrelevant. It is required to be removed from one place.

![Screenshot 2024-05-26 092844](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/89777420/cd2ee04b-cdf9-44f7-ad3a-7e836a11faa5)

![Screenshot 2024-05-26 092452](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/89777420/9d36effb-f1a1-48ae-a34c-d86067ff678c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vaishali-sharma-20** [comment]
Please assign this to me. I can improve it.

**Comment by CSEdgeOff** [comment]
@vaishali-sharma-20 Thanks for the patience what will you replace their instead of contact section any ideas..?

**Comment by vaishali-sharma-20** [comment]
@CSEdgeOff Sorry for the late reply but I was looking for the best
I have a few ideas to enhance our webpage that we can add instead of contacting us section:
1. Signup and Login Option that will personalize user experience and improve retention.
2. Trending Blogs Section to increase engagement by showcasing popular content.
3. Feedback Section that gathers user insights to improve our offerings.

**Comment by CSEdgeOff** [comment]
@vaishali-sharma-20 As you already working on the form place that form in that place.
and make it simple and minimalistic.

**Comment by vaishali-sharma-20** [comment]
@CSEdgeOff Please review it and let me know if any changes are needed. and also please add labels to this task.
