### ISSUE TITLE
[Feature]  Pre-Loader for CSEdge

### ISSUE THREAD

**Issue by sakshi261203** [CSEdgeOfficial/learn.csedge.courses#299]
### Description

Hi CSEdgeOff,

I'm writing to express my interest in contributing to the website by implementing a preloader. I've been following the project for a while now and I'm impressed with the organization's mission.

I believe a preloader would be a valuable addition to the website by improving user experience in the following ways:

**Reduced perceived load time**: A preloader can make the website feel faster by giving users something to look at while content loads.
**Enhanced brand image**: A creative preloader can serve as a micro-interaction that reflects the organization's design aesthetic.
I've been working with web development and have experience implementing preloaders using libraries. I'm confident I can create a preloader that is both visually engaging and technically sound. The preloade I added is changing the color with the time also.

I'd be happy to discuss this further and explore the most suitable preloader design for the website. I'm available to take on this task whenever you see fit.

Thanks for your time and consideration.

Sincerely,
Sakshi

Please assign this task to me ....

### Screenshots

![Screenshot (6886)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/163162219/6775cb06-104d-45ff-8dd9-9a43ca07a113)

![Screenshot (6887)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/163162219/5d6327ac-bd3c-42d6-af7c-cab9b005b2d4)
![Screenshot (6888)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/163162219/56ab0864-1081-4368-a37f-024a426428d7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@sakshi261203 Those above aren't creative i think 
Would you like to work on more customized once
Like the C need to be highlighted and zoom out it set some size and fade in the name CSEdge 

Would you do this..?

**Comment by sakshi261203** [comment]
Sure, I'll do that...

**Comment by sakshi261203** [comment]
Here, it is...

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/163162219/309a8b46-d474-478e-aebb-0ed56c154803

**Comment by sakshi261203** [comment]
Is it okay , or else you want something add in it?

**Comment by sakshi261203** [comment]
Could you please assign this task to me...

**Comment by CSEdgeOff** [comment]
> something

Keep it simple not like fancy things
It's a company domain that needs to be professional and minimalistic
make that as I mentioned above earlier

**Comment by sakshi261203** [comment]
ok

**Comment by sakshi261203** [comment]
Here it is....

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/163162219/aaf82573-4ac5-4ba7-8adc-fd2bd79159e5

**Comment by sakshi261203** [comment]
Is it okay Sir....

**Comment by nileshsn** [comment]
Hi @CSEdgeOff ,

I would like to work on the "Pre-Loader for CSEdge" feature as part of GSSoC'24. Could you please assign this issue to me? I am eager to contribute and have experience with similar tasks. I will keep it simple and professional.

Thank you!

**Comment by drick-infinity** [comment]
https://github.com/CSEdgeOfficial/learn.csedge.courses/pull/400

**Comment by MadalapureVaishnavi** [comment]
I would like to work on this issue can yyou assign it to me

**Comment by solanki505** [comment]
I would like to work on this  issue 
![Uploading Screenshot 2024-06-24 123531.png…]()
