### ISSUE TITLE
Design a good Frontend to display the code snippets in the articles

### ISSUE THREAD

**Issue by CSEdgeOff** [CSEdgeOfficial/learn.csedge.courses#3]

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
can you assign this to me, i can work on it

**Comment by CSEdgeOff** [comment]
Could you please provide the details of what tech stack you use to solve this issue

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
i am going to use the same techstack as you mentioned in the readme
Frontend: HTML5, CSS3, JavaScript, BootStrap
IDE: VS Code/Google IDX
Version Control: Git and GitHub

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
to make the code snippet look beautiful i can use prism along with some additional libraries like copy to clipboard

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/136828553/e6432e7d-06bc-457d-abfa-c3a8caf9cbd1)
here is a demo

**Comment by CSEdgeOff** [comment]
@DEV-Soumya-Ranjan-Swain make it more good add a copy icon in the button `copy code` and demonstrate it by adding an article and implement that code snippet in that article.
Have any doubts kindly send you contact.
