### ISSUE TITLE
BUG: Footer Links Needs Hovering Effect

### ISSUE THREAD

**Issue by jency1** [CSEdgeOfficial/learn.csedge.courses#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer links on our website currently do not have a hovering effect, which can make the user interface feel less interactive and engaging. Adding a hovering effect to these links will improve the user experience by providing visual feedback when users interact with them.

Adding a hover effect to links is a common practice that enhances usability and provides a more polished and interactive user experience.

Also the "about" link in the footer section is not working. Ideally it should redirect to the about section on the page.

I'm GSSOC'24 Contributor.

Please assign this issue to me, as I would like to solve this bug as soon as possible.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
@jency1 Need more details on your Issue how would be the output.?

**Comment by jency1** [comment]
@CSEdgeOff Can I start working on this issue?
