### ISSUE TITLE
[Technical writing] Write an article on GitHub Pages and How to use it.

### ISSUE THREAD

**Issue by Durgesh-Vaigandla** [CSEdgeOfficial/learn.csedge.courses#303]
### What's the style idea?

We need to improve

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by vaishali-sharma-20** [comment]
Hello @CSEdgeOff, I would like to contribute to Content writing. Please assign this to me.
