### ISSUE TITLE
Home page , [feature} smooth scrolling and responsiveness 

### ISSUE THREAD

**Issue by unnatinarayan** [CSEdgeOfficial/learn.csedge.courses#31]
In the site the opening page is not the home page but the blog page. I want to correct this issue, also the blog / course page is not properly styled. I want to implement smooth scrolling and mobile responsive. Please assign me this issue @Durgesh-Vaigandla 
[screen-capture (2).webm](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/150275983/77d90e1e-29f1-47fa-927e-3812756e39d7)

**Comment by Durgesh-Vaigandla** [comment]
We setup like that purposefully.

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by unnatinarayan** [comment]
Then please assign me this issue. Then i will work over the responsiveness and smooth scrolling of the website.
I will contribute under GSSOC'24.
