### ISSUE TITLE
[Style] Improve Search Bar Result 

### ISSUE THREAD

**Issue by RickyParte** [CSEdgeOfficial/learn.csedge.courses#32]
### What's the style idea?

We need to improve that search result like these 
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/77445318/9a568421-ed02-47d5-be94-a4a0ce4a32ef)
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/77445318/ff9406c1-7fc3-44c9-915e-247fe46bebad)

I am ready with these changes. if you assigned this issue to me Ill raise PR as soon as possible.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
Good
