### ISSUE TITLE
BUG:Pagination is not working in blog section 

### ISSUE THREAD

**Issue by Yashgabani845** [CSEdgeOfficial/learn.csedge.courses#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### we can not move anywhere by clicking number ans older,newer links as  well
![Screenshot (183)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/127788321/8d503ea4-fca8-4acd-85f3-7cbf3b662a52)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Yashgabani845** [comment]
@Durgesh-Vaigandla @CSEdgeOff 
 i want to work on this issue please assign m this issue

**Comment by CSEdgeOff** [comment]
@Yashgabani845 Make sure that new page needs to display remaining posts which are in the posts folder

**Comment by MadalapureVaishnavi** [comment]
I want to work on this issue can you assign me this issue
