### ISSUE TITLE
About CSEdge

### ISSUE THREAD

**Issue by prasukjain07** [CSEdgeOfficial/learn.csedge.courses#324]
### What's the style idea?

Need help and learn more sections are not properly align

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/115997785/37454e39-9683-4217-aa14-b0192a2b642b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by MadalapureVaishnavi** [comment]
Hi, I would like to work on this issue. Can you please assign it to me?

**Comment by prasukjain07** [comment]
Please check the PR
