### ISSUE TITLE
[Feature] <Login and Signup page>

### ISSUE THREAD

**Issue by rajkrsingh9** [CSEdgeOfficial/learn.csedge.courses#33]
### Description

Please assign me this issue, I will work on creating login and signup page also will add forgot password and reset password page.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
It's a static website doesn't need the login and signup.
The sole purpose of this website to help our interns.
