### ISSUE TITLE
BUG: Require changes in the Previous and Next section for better appearence

### ISSUE THREAD

**Issue by Ankur-Rai-19** [CSEdgeOfficial/learn.csedge.courses#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current look:
![next prev prob](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125396300/50d163c8-cdfa-4d98-aa1d-cd21d07acde7)

### After Changes somewhat like this:
![Capture](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125396300/17e1405b-1bed-492b-ba0c-309192069d99)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kavita1928** [comment]
i want to work for this task to improve the code for better apperances
