### ISSUE TITLE
BUG:Two contact us button in navbar

### ISSUE THREAD

**Issue by jayraj175coder** [CSEdgeOfficial/learn.csedge.courses#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There will be no need for two contact us buttons in navbar.
I want to remove one from this.
Could you assign me this issue under gssoc24??
![Screenshot 2024-05-29 233445](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/135996214/1d1ca3f8-7607-4a6d-aefe-19dd17b5f0e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kavita1928** [comment]
i want to work on this project

**Comment by 22-0304** [comment]
Can you assign me this issue @jayraj175coder

**Comment by vaishali-sharma-20** [comment]
Hello @CSEdgeOff and @Durgesh-Vaigandla , I am GSSoC'24 contributor. Can you please assign me this issue as a task? I would love to do this.
