### ISSUE TITLE
BUG:navbar issue in desktop mode.

### ISSUE THREAD

**Issue by jayraj175coder** [CSEdgeOfficial/learn.csedge.courses#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I see your website heading is hidden by navbar. 
I want to work under gsoc24.
![Screenshot 2024-05-29 233512](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/135996214/30cd8251-52fd-4a50-91a5-b71dab59d175)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vaishali-sharma-20** [comment]
Hello @CSEdgeOff and @Durgesh-Vaigandla , I am GSSoC'24 contributor. Can you please assign me this issue as a task? I would love to do this.

**Comment by jayraj175coder** [comment]
Hi @CSEdgeOff this task is completed and issue is solved.
COuld you merged this I submit PR...
