### ISSUE TITLE
Improving the design of home page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [CSEdgeOfficial/learn.csedge.courses#34]
### What's the style idea?

I am a UI UX designer and Frontend developer. I can change the style of the website using the latest design trends following the correct visual hierarchy, typography and colour schemes. 

Please assign this issue to me under GSSoc'24 (Level-3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by ArjitaSahu123** [comment]
I am a frontend developer working on mern stack .I can make the UI interactive from my tech skills.

**Comment by FatemaBaig** [comment]
Hello, i am interested in this part. Please assign it to me.
