### ISSUE TITLE
Improving UI including header, footer and DIVs

### ISSUE THREAD

**Issue by aaryancodeshere** [CSEdgeOfficial/learn.csedge.courses#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# UI Design bugs

There are several issues with the UI.

- The header and footer are not responsive.

- News divs are not arranged properly.

- Many minor bugs.

 It should be corrected.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhisek2004** [comment]
Hey, I would like to contribute please allow me to work on this issue.
Thank you
