### ISSUE TITLE
Make Pagination Functional 

### ISSUE THREAD

**Issue by infycorn** [CSEdgeOfficial/learn.csedge.courses#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello mentor, I want to make the Newer, 1, 2, ... 15, Older Pagination feature functional! Could you kindly assign the issue to me and label the level? Thank you, mentor!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
We Didn't created lot content yet cause it's a new one so the pagination is useless in this case because we haven't created more content if you're willing to add both we'll assign to you.

**Comment by codewithinfiver** [comment]
> We Didn't created lot content yet cause it's a new one so the pagination is useless in this case because we haven't created more content if you're willing to add both we'll assign to you.

Okay mentor, I would add content and make the pagination functional! If you may assign and label the level of the same. Thank you!

**Comment by CSEdgeOff** [comment]
@codewithinfiver Kindly share your contact details.

**Comment by codewithinfiver** [comment]
> @codewithinfiver Kindly share your contact details.

Hello mentor, you can contact me at thehoimantidutta@gmail.com. Thank you, mentor.

**Comment by CSEdgeOff** [comment]
@codewithinfiver Did you start working on the issue?

**Comment by codewithinfiver** [comment]
> @codewithinfiver Did you start working on the issue?

Yes mentor, I have forked the repository and started working on the same locally. I will open a pull request shortly. Thank you, mentor!

**Comment by codewithinfiver** [comment]
> @codewithinfiver Did you start working on the issue?

Mentor I am also working on the content to be added, if any issues crop up, I will mail you. Could you provide your contact details for the same?

**Comment by CSEdgeOff** [comment]
@codewithinfiver Text here +91 79956 65539

**Comment by codewithinfiver** [comment]
> @codewithinfiver Text here +91 79956 65539

Thank you, mentor!
