### ISSUE TITLE
[Style] Create fully responsive navbar

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [CSEdgeOfficial/learn.csedge.courses#356]
### What's the style idea?

We need to improve the css of the navbar to make it fully responsive for all devices for mobile devices i will add hamburger menu .

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by vermagithubcs** [comment]
I am interested in contributing to this issue, and I created a fully responsive navbar. Please assign me to work on this issue!
