### ISSUE TITLE
[Style] Change the font of index.html

### ISSUE THREAD

**Issue by ahuja05** [CSEdgeOfficial/learn.csedge.courses#359]
### What's the style idea?

We need to improve the font style of the index.html page.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by ahuja05** [comment]
![Screenshot (430)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/118765688/7c60422c-82d5-4850-9141-aecb883c652a)
Please assign and label this issue.

**Comment by ananyag309** [comment]
Hey, i have started contributing since today, till now i have 0 pr but why my name github acc is not there. git acc ananyag309

**Comment by Gokilp** [comment]
I will working on issue please assign to me
