### ISSUE TITLE
BUG: Added hovering effects to cards in page

### ISSUE THREAD

**Issue by SuhainaFathimaM** [CSEdgeOfficial/learn.csedge.courses#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/153417476/3302c8bb-d55e-43b6-8fb6-d7ae867d5ba5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gokilp** [comment]
Can asssign to me I working on issue under Gssoc 24
