### ISSUE TITLE
BUG: Require changes in Footer 

### ISSUE THREAD

**Issue by Ankur-Rai-19** [CSEdgeOfficial/learn.csedge.courses#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# Description
### The Footer does not have the same design in all the sections like in the HOME and Free Content Page. The appearance of the footer should be the same as the Blog Footer page. The Content remains the same but the design is required to be changed for a better appearance.

The Required changes are in the HOME and Free Content Page of the Footer.

## Current Look:
![footer prob](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125396300/cba71dff-9244-4842-ac7b-c4f975c2c096)

## After changing how the footer Look like (Just a sample)
![sample of footer](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125396300/37b33de1-dd60-4339-ba69-158595cbafe4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gokilp** [comment]
Can asssign to me I working on issue under Gssoc 24
