### ISSUE TITLE
[Feature] Addition of Preloader and Custom Cursor

### ISSUE THREAD

**Issue by Anjaliavv51** [CSEdgeOfficial/learn.csedge.courses#378]
### Use Case

Preloader gives user idea about the loading and cusor looks cool while pointing.

### Benefits

1.Enhanced User Experience
2.Personalization and Branding
3.Creative Expression

### Screenshots

![image](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/f4162b47-edcc-4869-9b68-0013f8898d37)

https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/assets/154777864/e111595d-804c-4638-a2c9-02f1f4a33bab

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Anjaliavv51** [comment]
@sanjay-kv please assign this issue

**Comment by CSEdgeOff** [comment]
#382 PR is in Under review 
#381 Check out this added some info about the Pre Loader work if you can capable to doing that and make PR

**Comment by Anjaliavv51** [comment]
@CSEdgeOff custom cursor is also in the same PR
