### ISSUE TITLE
BUG: No hovering effect on 'Contact Us' icons

### ISSUE THREAD

**Issue by Ajita369** [CSEdgeOfficial/learn.csedge.courses#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no hovering effect on the icons in this section .
Here is screenshot of the section : 
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/162597493/0f441666-0446-446b-9760-0583912210f9)
I will like to work on this issue, please assign this to me under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
#311 Already the PR is in pending review
