### ISSUE TITLE
[Style] Add hover effect in navbar items and active link

### ISSUE THREAD

**Issue by aryansharma220** [CSEdgeOfficial/learn.csedge.courses#38]
### What's the style idea?

We need to improve the nabvar links to add hover effect and show which item is activeIs there an existing issue for this?
 
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/133234867/f2d2c9f8-daff-4ef1-a376-d05cbc00727a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

@CSEdgeOff Please assign it to me

**Comment by CSEdgeOff** [comment]
@aryansharma220 You need to work on blog page not in main page both are different domains.
