### ISSUE TITLE
Add a preloader

### ISSUE THREAD

**Issue by Saipradyumnagoud** [CSEdgeOfficial/learn.csedge.courses#381]
#gssoc24

**Comment by CSEdgeOff** [comment]
@Saipradyumnagoud  Need a Custom pre loader
which represents the company Logo and Name with little animations 
the pre loader need to be clean not fancy.

**Comment by drick-infinity** [comment]
https://github.com/CSEdgeOfficial/learn.csedge.courses/pull/400 
check this pull request
