### ISSUE TITLE
Adding more Recent posts and category section

### ISSUE THREAD

**Issue by Bhumika1312** [CSEdgeOfficial/learn.csedge.courses#387]
### Description

I want to add more recent posts to the blog section and also want to link the category sections of the recent post to Google so that when clicked, it directs to Google.

### Screenshots

Recent post:
![Screenshot 2024-06-02 085949](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/115869626/869ca791-01dd-4c28-9608-e3699165a689)

Category section: 
![Screenshot 2024-06-02 090004](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/115869626/7d3e2b02-81c1-4cd2-aa82-3f397536e4ac)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by vaishali-sharma-20** [comment]
@CSEdgeOff and @Durgesh-Vaigandla, I am interested in contributing additional technical blogs to our project. Having already contributed some technical content, I am eager to further enhance our repository with more valuable insights and tutorials on relevant topics.
I would like to proceed with this task. Please let me know if there are any specific guidelines or topics you would like me to focus on.

**Comment by CSEdgeOff** [comment]
@vaishali-sharma-20 Having any ideas of what to implement in the web like a feature or the posts that our interns asks us frequently.
This is our company number text here
[https://api.whatsapp.com/send/?phone=917995665539&text=Hello+from+GitHub&type=phone_number&app_absent=0](Click here)

**Comment by Bhumika1312** [comment]
@CSEdgeOff  can you please assign this issue to me under the GSSOC'24 contributor
