### ISSUE TITLE
Make navbar fixed

### ISSUE THREAD

**Issue by pankhuri92** [CSEdgeOfficial/learn.csedge.courses#388]
### What's the style idea?

While scrolling down, if the navbar remains fixed hanging on top, it would be easier for access. Kindly assign me the issue under gssoc'24

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/138357063/6ae45f8a-775d-4b0a-a843-1489223c57ef

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Aashka19** [comment]
plz assign it to me under gssoc 24
