### ISSUE TITLE
BUG: Make site responsive

### ISSUE THREAD

**Issue by pankhuri92** [CSEdgeOfficial/learn.csedge.courses#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The home page is not responsive enough. It has got the horizontal scroll in other versions. Kindly assign me the issue under gssoc'24.
![Screenshot 2024-06-02 183022](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/138357063/40167810-b956-44a5-9f75-b5fead9383c9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
@pankhuri92  Work only on desktop view 
don't make any changes in other unnecessary files

**Comment by KavyaBS123** [comment]
Hey @CSEdgeOff I am GSSOC Contributor can you please assign this issue to me I would be glad to work on it!

**Comment by pankhuri92** [comment]
@CSEdgeOff, yes I'll try not to affect other files. Also, desktop view seems fine, its the views smaller than laptop-1024px that aren't responsive.
