### ISSUE TITLE
BUG: Spelling error

### ISSUE THREAD

**Issue by AkhilaSunesh** [CSEdgeOfficial/learn.csedge.courses#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/140897461/b2f90f88-f017-46bc-8248-058b3efff25e)
Comming Soon should be replaced with Coming Soon
Kindly assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aashka19** [comment]
plz assign it to me under gssoc 24

**Comment by Gokilp** [comment]
Can asssign to me I working on issue under Gssoc 24
