### ISSUE TITLE
Backend service for mailing contact form information

### ISSUE THREAD

**Issue by atharvarekhawar** [CSEdgeOfficial/learn.csedge.courses#396]
### Description

I would like to create a nodemailer service using node.js backend which will connect with frontend contact form and let user's send messages from the contact form to the project admin.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by atharvarekhawar** [comment]
@CSEdgeOff please assign this issue to me.

**Comment by CSEdgeOff** [comment]
@atharvarekhawar We are using google services 
so that would be not necessary
