### ISSUE TITLE
[Technical Writing] Web Scraping Tool with BeautifulSoup

### ISSUE THREAD

**Issue by CSEdgeOff** [CSEdgeOfficial/learn.csedge.courses#399]
### Description

Write a clear article on using Beautiful soup Lib 
Develop a web scraping application using Python's Beautiful Soup library. Extract data from a website and present it in a structured format (e.g., CSV, JSON).

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Unalia09** [comment]
Hello @CSEdgeOff do I only need to write a article and a python script using the beautiful soup lib or also code everything like where to place it and all?

**Comment by CSEdgeOff** [comment]
@Unalia09 Not completely interns need to understand how to do the web scrapping using Beautiful soup 
So Take a simple example by yourself and try to explain it provide little documentation so that they can be able to perform their tasks according that

**Comment by Unalia09** [comment]
@CSEdgeOff Thankyou for the information, I would like to work on this task. Can you please assign it to me?

**Comment by vaishali-sharma-20** [comment]
Hello @CSEdgeOff and @Durgesh-Vaigandla  , I would like to contribute to the technical content writing of [Web Scraping Tool with BeautifulSoup. I request that you assign me this task and I will ensure users have a comprehensive guide to effectively use BeautifulSoup for web scraping.

**Comment by lassmara** [comment]
please assign me this issue
