### ISSUE TITLE
Improving "categories" and "recent posts" section for Enhanced User Experience

### ISSUE THREAD

**Issue by Aditi323** [CSEdgeOfficial/learn.csedge.courses#4]
![Screenshot (354)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/114893448/ee499d28-96fb-4980-970f-b79b6db51244)
I want to fix the "categories" and "recent posts" section as it appears as links 
Please assign this to me under GSSOC'24

**Comment by imanasdash** [comment]
I can do it . If someone inactive and unable to do so , then Please it to me
