### ISSUE TITLE
[Style]Style the links 

### ISSUE THREAD

**Issue by aryansharma220** [CSEdgeOfficial/learn.csedge.courses#40]
### What's the style idea?

We need to improve the styling of the links
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/133234867/8650ca12-fa91-48c6-b805-71d34a965023)

@CSEdgeOff  please assign it to me

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@aryansharma220 Lot of people are working on this thing if you make you PR first we'll merge that first.
Please start working on that.

**Comment by aryansharma220** [comment]
I am not able to do a pull request, I am getting the error 
$ git push origin styleLinks
remote: Permission to CSEdgeOfficial/learn.csedge.courses.git denied to aryansharma220.
fatal: unable to access 'https://github.com/CSEdgeOfficial/learn.csedge.courses/': The requested URL returned error: 403

@CSEdgeOff please can i get some help how to solve this problem
