### ISSUE TITLE
[Style]: Need To Add to Hover Effect and many more

### ISSUE THREAD

**Issue by CodeXsubham** [CSEdgeOfficial/learn.csedge.courses#401]
### What's the style idea?

We need to improve
- Hover Effect
- Text Styles
- Need to Add 24/7 Chatbot
- Add Feedback Form
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/119094596/e3947d6d-620d-4830-9a80-008d818afb5e)

Please Assign this  to me so that I can work on enhancement of the user Experience , Thankyou

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CodeXsubham** [comment]
@CSEdgeOff Please Assign , so that I can Contribute for the enhancement of the website

**Comment by CSEdgeOff** [comment]
@CodeXsubham That a live web 
The developing one is here check out this once 
[https://learn.csedge.courses/csedge.courses/index.html](https://learn.csedge.courses/csedge.courses/index.html)
[https://learn.csedge.courses/home.html](https://learn.csedge.courses/home.html)

**Comment by CodeXsubham** [comment]
@CSEdgeOff Still Navbar and Footer need some enhancement

**Comment by CodeXsubham** [comment]
@CSEdgeOff Still Footer Need to be fixed . 
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/119094596/f98078f6-f94a-4d69-a525-259a59c87079)

**Also Checkout my last contribution**

![Screenshot 2024-06-04 131435](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/119094596/bb83fe5a-ceb7-43f4-9105-5ccbcec38556)

**Comment by CSEdgeOff** [comment]
@CodeXsubham 

Let me know some things 
Don't use bootstrap in the main one csedge.courses

**Comment by CodeXsubham** [comment]
@CSEdgeOff Ok

**Comment by Speedysays01** [comment]
@CSEdgeOff please assign the task to me. I can help improve styling elements too!
