### ISSUE TITLE
[Feature] Add Social Media Buttons to share the articles in various social media platform

### ISSUE THREAD

**Issue by CSEdgeOff** [CSEdgeOfficial/learn.csedge.courses#402]
### Description

[Feature] Add Social Media Buttons to share the articles in various social media platforms Include the SEO for the better results

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by KavyaBS123** [comment]
Hey @CSEdgeOff I am GSSOC Contributor can you please assign this issue to me I would be glad to work on it!

**Comment by Gokilp** [comment]
Can asssign to me I working on issue under Gssoc 24

**Comment by KavyaBS123** [comment]
Have sent the pull request Please accept it!
