### ISSUE TITLE
BUG: Google form error

### ISSUE THREAD

**Issue by AkhilaSunesh** [CSEdgeOfficial/learn.csedge.courses#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/140897461/fa0fe9c6-05ae-4e9e-bf70-1cf623867418)
The internship date starts before the deadline for applying.
There is an error in the time schedule.
I can't work on this issue. But I have some suggestions for this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by kashvi9** [comment]
Hello @CSEdgeOff 
I can work on this issue, if assigned under GSSOC'24.
This issue exists in all the forms
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/169376061/dd7957aa-be0a-41ec-b74d-c86d799adfde)
