### ISSUE TITLE
[Style] Make the whole search bar Hover/New Search bar

### ISSUE THREAD

**Issue by CSEdgeOff** [CSEdgeOfficial/learn.csedge.courses#41]
### What's the style idea?

Make the hover would apply including the button 
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/162341620/80a1d1cf-51c4-4367-b935-d4ea773eaadf)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Santhosh-Siddhardha** [comment]
Hi @CSEdgeOff ,
I am interested on working with this issue. Could you please assign me this issue.

**Comment by saswat733** [comment]
i can make this and also add my additional touches that you would loved to see kindly assign this task to me it's going to be my first contribution would give my best !

**Comment by kairveeehh** [comment]
@CSEdgeOff  i would like to contribute to this .

**Comment by Mystery-Shashwat** [comment]
**@CSEdgeOff** I want to contribute on this issue .Please assign me this issue

**Comment by srushtiss** [comment]
@CSEdgeOff This could be my first contribution if you would assign me

**Comment by SalehaTabassum** [comment]
Hi @CSEdgeOff I would like to work on this issue under gssoc . Please assign this to me

**Comment by Rehan52004** [comment]
I want to work on it, please assign me this issue.

**Comment by SalehaTabassum** [comment]
Hi @CSEdgeOff please assign this issue.i have experience of making websites.i have already made Spotify, Netflix and Amazon clone so I think I can better solve this issue

**Comment by sinchana0m** [comment]
I am interested in contributing to this project.I would request you to assign me the issue.

**Comment by sapana1579** [comment]
@CSEdgeOff Hello, I really like your project idea and here to contribute to your project as a GSSoC"24 contributor so assign me this issue.

**Comment by Debarunn1806** [comment]
@CSEdgeOff  Hello I can implement this quickly and would like to contribute under GSSOC"24 please assign me this issue.

**Comment by A032003** [comment]
Hi @CSEdgeOff I would like to work on this issue under gssoc . Please assign this to me

**Comment by yash21sriv** [comment]
hey please assign the issue to me under GSSOC

**Comment by Japneet001** [comment]
@CSEdgeOff Pls assign this issue to me under GSSOC'24

**Comment by CSEdgeOff** [comment]
Keep the Assigning aside work on the thing make the PR's, who gives the best o/p. Their PR will be merged.!

**Comment by Gokilp** [comment]
please assign to me @CSEdgeOff

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and I would love to contribute, can you please assign me this issue.
