### ISSUE TITLE
[Feature] want to add hover effect to different boxes

### ISSUE THREAD

**Issue by Shreyaa173** [CSEdgeOfficial/learn.csedge.courses#418]
### Description

want to add hover effect to different boxes

### Screenshots

![Screenshot 2024-06-06 171613](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/144673309/8a41c671-8e21-4308-a8c8-792a8f148e69)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by MadalapureVaishnavi** [comment]
Assign this issue to me
