### ISSUE TITLE
[Style] make the content centre align also make a new navbar

### ISSUE THREAD

**Issue by saswat733** [CSEdgeOfficial/learn.csedge.courses#42]
### What's the style idea?

We need to improve the ui and also make the new navBar having the search  

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
The Idea was good but we can't apply the same approach on the mobile view. Is there any solution for that?

**Comment by saswat733** [comment]
I'll make the navbar responsive and the center aligning can be done like we will display all the cards vertically one after other i can also improve the ui make it look more pleasing
