### ISSUE TITLE
BUG: Extra Card in the home page

### ISSUE THREAD

**Issue by arpy8** [CSEdgeOfficial/learn.csedge.courses#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There's an extra empty card in the website's home page

Attaching screenshot for reference:
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/74809468/c375097f-be85-414d-97fb-694f3ffa1ccc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Durgesh-Vaigandla** [comment]
That box is to display ads Maybe you have an ad blocker that's the reason it didn't shown up
