### ISSUE TITLE
[Style] Fixing the UI of the homepage

### ISSUE THREAD

**Issue by HarshitGupta1511** [CSEdgeOfficial/learn.csedge.courses#428]
### What's the style idea?

We need to improve . as we enter the webpage it looks simple and not at all attractive . I want to add various hover effects new texts as well as icon and make same colours changes to make homepage attractive and user friendly .
please assign this issue to me @CodeXsubham 
<img width="1428" alt="Screenshot 2024-06-08 at 3 05 53 PM" src="https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/120268295/fa97e01b-c2fe-4978-a87b-3e88e27f6299">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CodeXsubham** [comment]
I'm not  project admin @HarshitGupta1511  tag @CSEdgeOff

**Comment by HarshitGupta1511** [comment]
@CSEdgeOff please assign this task to me

**Comment by sarthaksharma39** [comment]
@CSEdgeOff  I would like to work on this issue. It would be great if you assign this to me. I will do this in 1 or 2 day.
Thank you
Your sincerely,
Sarthak Sharma
