### ISSUE TITLE
scroll down progress bar missing

### ISSUE THREAD

**Issue by paulkrishanu4** [CSEdgeOfficial/learn.csedge.courses#429]
### Description

want to add scroll down progress bar to all the pages of this site like this

### Screenshots

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/169196836/6044c429-41fe-4479-be92-6e51246fea4d

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Durgesh-Vaigandla** [comment]
The feature Exists already check the website properly
