### ISSUE TITLE
footer components can be improved because margin and spacing is not consistent here

### ISSUE THREAD

**Issue by Prnasin** [CSEdgeOfficial/learn.csedge.courses#430]
### What's the style idea?

We need to improve spacing in footer section 

![Screenshot 2024-06-09 091054](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125786433/da0a4852-06c4-4ca2-9bb4-ca0f3c86628f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by sakeel-103** [comment]
@CSEdgeOff 
Please assign me this task under gssoc'24.
I will fix the footer section alignments and all.
