### ISSUE TITLE
[Feature] Navbar sections have no hover effect.

### ISSUE THREAD

**Issue by sakeel-103** [CSEdgeOfficial/learn.csedge.courses#431]
### Description

In Navbar section there is no hover effect.
Please assign me this task I'll add this effect with attractive color effect.

### Screenshots

Below is the video of that. 

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/136844498/09a519b0-7f89-47a5-b188-e4f586d24973

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**

**Comment by anshikatiwari20** [comment]
**Description**

The hover effect on the navbar section can be made more appealing, and I have some ideas to enhance the user experience. Please assign this issue to me. I would like to take up this issue as part of GSSoC. 

**Screenshot**

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/143124119/f924f783-3945-47c3-a57a-1d104113b11a

Thank you!

**Comment by CSEdgeOff** [comment]
@anshikatiwari20 We have that in the website already just didn't updated to the main 
[Checkout here](https://learn.csedge.courses/home.html)
