### ISSUE TITLE
Style: REVAMP FOOTERSECTION AND ADD HOVER EFFECT IN NAVBAR

### ISSUE THREAD

**Issue by AbhinaySngh** [CSEdgeOfficial/learn.csedge.courses#433]
### What's the style idea?

We need to improve footer section alingment , spacing and hover effect in navbar
![Screenshot 2024-06-09 202314](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/162811933/1325bbab-1a85-4940-bc66-2381ac2b93cc)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by AbhinaySngh** [comment]
@Durgesh-Vaigandla please assign me this issue under GSSOC'24 label.

**Comment by sakeel-103** [comment]
@CSEdgeOff 
assign me this task under gssoc'24 and level 3.
I'll fix this issue.
