### ISSUE TITLE
Add a Rate us option

### ISSUE THREAD

**Issue by sailaja-adapa** [CSEdgeOfficial/learn.csedge.courses#439]
### Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by sailaja-adapa** [comment]
will you assign me this issue @Durgesh-Vaigandla under GSSOC'24

**Comment by CSEdgeOff** [comment]
@sailaja-adapa We actually don't need that feature 
could you work on another feature 
Like we need a feature the need to embed in the articles to share the article into social platforms 
although need to add the necessary SEO Context to work more efficiently

**Comment by sailaja-adapa** [comment]
may be i can't do that i am new to contributing @CSEdgeOff assign that to another person
Thank you so much for considering me for that issue

**Comment by vaishali-sharma-20** [comment]
Hello @CSEdgeOff, I request you to assign this task to me.
