### ISSUE TITLE
Add Icons to options on Navbar in home page

### ISSUE THREAD

**Issue by sailaja-adapa** [CSEdgeOfficial/learn.csedge.courses#440]
### Description

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add icons to options in home page it will make our website to look attractive 

Can you please assign me this issue under gssoc'24 @Durgesh-Vaigandla 

### Screenshots

![cse](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/161804629/6410f916-db76-4b03-909e-29ccd640a570)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@sailaja-adapa Already Done 
We didn't added that to the main cause didn't fit there.
