### ISSUE TITLE
Adding hover effects to icons

### ISSUE THREAD

**Issue by Speedysays01** [CSEdgeOfficial/learn.csedge.courses#443]
### What's the style idea?

I can add the on-hover style change effect to all the social media icons and Important buttons like 'Read-me' , 'contact us' etc. This small change can make the UI more responsive making the website more interactive.
Please assign this issue to me under GSSoC24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Unknnown-Mayank** [comment]
**Description:**
I would like to enhance the user interface by adding on-hover style changes to all social media icons and important buttons such as 'Read-me', 'Contact Us', etc. This will make the website more interactive and responsive.

**Proposed Changes:**

- Add hover effects to social media icons in the footer/header.

- Add hover effects to important buttons on the homepage and other key sections.

- Ensure that the styles are consistent with the overall design language of the website.

**Why This is Needed:**
Hover effects provide visual feedback to users, making the interface feel more responsive and interactive. This small enhancement can significantly improve user experience.

**Additional Context:**
I am participating in GSSoC24 and would like to contribute by making these UI improvements. Please assign this issue to me so I can start working on it.

**Comment by Riyasharma1311** [comment]
please assign me this issue
