### ISSUE TITLE
Sign Up and Login page

### ISSUE THREAD

**Issue by Syed0206** [CSEdgeOfficial/learn.csedge.courses#45]
I would like to add Sign Up and Login Page to website @CSEdgeOff can u please assign this issue under GSSOC'24

**Comment by komalgururanii** [comment]
After reviewing the current tasks, I believe I can offer valuable input by working on the SignUp and Login pages. I would be grateful if you could consider assigning me the SignUp and Login page task. Please let me know if there are any specific requirements or guidelines I should follow.

Thank you for considering my request. I look forward to your response.

**Comment by CSEdgeOff** [comment]
@Syed0206 and @komalgururanii There is no use and necessary of the signup and login pages in this website. work on any other tasks

If you're more interested to work this kind we have a Application form which is filled by the interns try to make connection both of them for more info text here 7995665539
