### ISSUE TITLE
Adding hover effects to the intership cards of the internship web page

### ISSUE THREAD

**Issue by sahithinandikula** [CSEdgeOfficial/learn.csedge.courses#450]
### What's the style idea?

We need to improve the style of internship cards by adding suitable hover effects and adjusting the alignment of cards making them position in the right way.
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/138794574/f1e8c3e3-ebe8-47a9-86cf-e0fb3529e84b)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Riyasharma1311** [comment]
please assign me this issue
