### ISSUE TITLE
BUG: blog page is opening first

### ISSUE THREAD

**Issue by mehrun171** [CSEdgeOfficial/learn.csedge.courses#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Initially as we click the link for the website and open it...instead of home page, blogs page is being visible at the beginning....this have to be solved as...when we click on the website link it should open home page first...
![Screenshot 2024-06-14 234408](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/116735695/178aac89-0999-417a-909b-a964cad9bbc5)
 please assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
@mehrun171 Because both are running on different domain learn.csedge.courses for Blog and csedge.courses for the main one
