### ISSUE TITLE
[Feature] : Implement the `Dark` and `Light` mode

### ISSUE THREAD

**Issue by sivaprasath2004** [CSEdgeOfficial/learn.csedge.courses#458]
### Description

- In this website cannot approach for the `Dark` and `light` mode, with User selection.
- i  want to work on this issue.
- please assign me..

### Screenshots

![Screenshot from 2024-06-15 07-36-03](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/121082414/7887a3d2-d89f-4dc2-9153-08d05789c458)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by sakeel-103** [comment]
@CSEdgeOff 
can you assign me this under gssoc'24.
