### ISSUE TITLE
[Feature] Display the articles dynamically using JS

### ISSUE THREAD

**Issue by Durgesh-Vaigandla** [CSEdgeOfficial/learn.csedge.courses#459]
### Description

Display the articles dynamically using JS 
Pagination also need to done Dynamically 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Ansh101112** [comment]
Want to work on this
