### ISSUE TITLE
Navigation Bar Icons Disappear When Scrolling

### ISSUE THREAD

**Issue by Syed0206** [CSEdgeOfficial/learn.csedge.courses#46]
### What's the style idea?

We need to improve When using the website, I noticed that the navigation bar icons become invisible when scrolling down the page. This behavior makes it difficult for users to navigate the website, as they lose access to important navigation elements.
![img1](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/123359660/8a0fffa1-ed82-48b6-b517-1a60d56cfea1)
![img2](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/123359660/767deac9-3237-4250-89e3-af4c836fee19)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
You need to work on learn.csedge.courses not on csedge.courses
This project is on only about blog which is running on separate domain.
