### ISSUE TITLE
[Feature] Make Contact Us Page

### ISSUE THREAD

**Issue by jency1** [CSEdgeOfficial/learn.csedge.courses#465]
### Description

Currently there is no contact us page for user to interact with the team, So contact us page needs to be added.

Please assign this issue to me.

@CSEdgeOff @Durgesh-Vaigandla 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Riyasharma1311** [comment]
please assign me this issue

**Comment by Ananya-Nair20** [comment]
Hello @CSEdgeOff,
 
I am interested in solving this issue. Please assign this issue to me under GSSOC'24 with appropriate gssoc level labels. 

Thank you
