### ISSUE TITLE
[Feature] Add Hover Effect in Navbar

### ISSUE THREAD

**Issue by jency1** [CSEdgeOfficial/learn.csedge.courses#466]
### Description

Currently no hover effect is there in navbar making it difficult to know on which link we are clicking. So Hover Effect in Navbar should be added as soon as possible for better user experience.

Please assign this issue to me under GSSOC'24.

@CSEdgeOff @Durgesh-Vaigandla  

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by jency1** [comment]
@CSEdgeOff Can I start working on this issue?

The navbar should have hover effect for the best user experience. To know where we are and to avoid clicking wrong links. 

Please assign this issue to me.
Thank you.

**Comment by Riyasharma1311** [comment]
please assign me this issue
