### ISSUE TITLE
Redesigning blog page (ss of idea)

### ISSUE THREAD

**Issue by kritzxd8** [CSEdgeOfficial/learn.csedge.courses#471]
### What's the style idea?

Hello @CSEdgeOfficial I'm Kritika a gssoc24 contibutor . We could change the style of the blogs page . Here's a picture of the design that we could implement.

![Screenshot 2024-06-16 185314](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/162461631/1d414515-960f-47ee-a815-3b73d97eef37)

This would be a great change for the project so kindly assign me this issue .

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@kritzxd8 Could you provide more details 
How it might look in the Mobile View..?

**Comment by kritzxd8** [comment]
@CSEdgeOff for mobile view it would look something like this 
below we'll add the footer . Also the extra white spaces around will be removed don't worry about that .

![Untitled design](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/162461631/653b27c2-7e03-4289-acfc-f725e09cdb6e)
