### ISSUE TITLE
[Feature] : Add subscribe to NewsLetter

### ISSUE THREAD

**Issue by Saipradyumnagoud** [CSEdgeOfficial/learn.csedge.courses#472]
### Description

Adding subscribe to news letter

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff  please assign me the issue

**Comment by CSEdgeOff** [comment]
@Saipradyumnagoud 
the same issue #398 was already open you need to use the code we provided their

**Comment by Saipradyumnagoud** [comment]
No need To take input of email ? @CSEdgeOff

**Comment by Saipradyumnagoud** [comment]
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/143107589/649ddd0d-9dff-49a8-afee-98035b3ca489)

it looks like ths @CSEdgeOff

**Comment by CSEdgeOff** [comment]
@Saipradyumnagoud Yes Basically the code was provided by LinkedIn Place it in a good spot like below About us description 
That make looks good

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff  yeah sure
