### ISSUE TITLE
[Feature] LOGO missing

### ISSUE THREAD

**Issue by kairveeehh** [CSEdgeOfficial/learn.csedge.courses#48]
### Description

add a logo

### Screenshots

would like to add a good logo

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@kairveeehh Added already
