### ISSUE TITLE
[Technical Writing] Write an article

### ISSUE THREAD

**Issue by CSEdgeOff** [CSEdgeOfficial/learn.csedge.courses#480]
### Description

How to make a Voice recorder application using Python and save the audio in the necessary formats 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by JagjeetChauhan** [comment]
@CSEdgeOff can you assign this task to me

**Comment by Durgesh-Vaigandla** [comment]
@vaishali-sharma-20 It was already assigned I can't do anything until the assigned person leave the issue.
You can work on another issues as we discussed earlier

**Comment by JagjeetChauhan** [comment]
[Voice recorder application using Python.docx](https://github.com/user-attachments/files/15909845/Voice.recorder.application.using.Python.docx)
@CSEdgeOff kindly check the article and give suggestions as well
