### ISSUE TITLE
Hover effect

### ISSUE THREAD

**Issue by Garima-149** [CSEdgeOfficial/learn.csedge.courses#483]
### Description

In the provided screenshot,links in navbar at landing page has not hover effect right now.I would like to add hover effect with some css.I feel that will improve its UI effectively.

### Screenshots

![Screenshot (67)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/143211271/8d1b72e3-9099-486f-9ad8-f56e12d023f5)
@CSEdgeOff     Please assign me this issue.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by sarthaksharma39** [comment]
It's an easy task. I have a experience in this. I would like to work on this issue. It would be great if you assign this to me.
Thank you
Your sincerely,
Sarthak Sharma
