### ISSUE TITLE
Add dark mode and light mode.

### ISSUE THREAD

**Issue by Deepanshi-05** [CSEdgeOfficial/learn.csedge.courses#487]
### Description

Add dark mode and light mode for the user's good experience.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by sarthaksharma39** [comment]
I would like to work on this issue. It would be great if you assign this to me. 
Thank you
Your sincerely,
Sarthak Sharma
