### ISSUE TITLE
[Feature] Testimonials feature 

### ISSUE THREAD

**Issue by kairveeehh** [CSEdgeOfficial/learn.csedge.courses#49]
### Description

testimonials play an imp part in enhancing a new user's trust and experience over the site and thereby i would like to design a page for the same that can be merged with the blogs or kept separate as well
### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Anamika-Ratna** [comment]
Hi there, I am willing to work on this issue, Kindly assign me this under gssoc tag.

**Comment by CSEdgeOff** [comment]
@kairveeehh Need the Screenshot of the place where you're going to add this feature.

**Comment by kairveeehh** [comment]
@CSEdgeOff I would like to add it in the blog feature , below certain cards of teh blogs ..."know what our users say" or "hear our users take" and teh whole feature 
### please assign it to me under gssoc'24

**Comment by CSEdgeOff** [comment]
@kairveeehh Make sure to update the repo before making changes because this repo may update frequently. and work faster to make your contribution.

**Comment by kairveeehh** [comment]
> @kairveeehh Make sure to update the repo before making changes because this repo may update frequently. and work faster to make your contribution.

sure I  will create the PR by the end of the day itself
