### ISSUE TITLE
[Feature] Add hover color

### ISSUE THREAD

**Issue by AkhilaSunesh** [CSEdgeOfficial/learn.csedge.courses#499]
### Description

Add hover color to the footer section

### Screenshots

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/140897461/c80a0fbf-5911-4fee-b15e-8192ea3481b7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by ansafnan20** [comment]
I would like to work on this issue.
