### ISSUE TITLE
BUG: Missing of Blog Title and placing the title of blog above the blog cover image

### ISSUE THREAD

**Issue by Rupa-Rd** [CSEdgeOfficial/learn.csedge.courses#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## **Missing of Blog Title**
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/102663541/5eeaea28-e07a-497e-8bd4-9b6a71395949)

This blog page doesn't have a blog title.

## **Position of existing blog title**
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/102663541/5303f2f8-971b-4acd-9ecb-86b878366124)

The title of the blog is placed below the blog's cover image. And it makes it difficult to find the title of blog that the user is currently reading.

## Proposed solution:
- Including titles for the blogs
- Placing the title of the blog above the cover image
- Highlighting the blog's title by increasing its size.

I have an experience in web development and would like to work on this issue, @CSEdgeOff, kindly assign this issue to me!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Durgesh-Vaigandla** [comment]
Ok @Rupa-Rd work on this we'll merge your PR

**Comment by Rupa-Rd** [comment]
Sure, @Durgesh-Vaigandla  can you assign this issue to me?
