### ISSUE TITLE
[Style] Adding hover effect in Navbar

### ISSUE THREAD

**Issue by HarshitGupta1511** [CSEdgeOfficial/learn.csedge.courses#504]
### What's the style idea?

We need to improve
hover effect on navbar looks much more attractive and amazing, I want to apply proper hover effect to the navbar links, please assign this task to me @DEV-Soumya-Ranjan-Swain @CSEdgeOff 
<img width="1437" alt="Screenshot 2024-06-22 at 10 46 48 PM" src="https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/120268295/6993cebf-4952-4871-9304-7fb5bf0bbf8b">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
@HarshitGupta1511 I am not the owner of this repo

**Comment by Aradhyajha** [comment]
Hello @Durgesh-Vaigandla .. i want to work on that issue please assign this task to me..i will complete this as soon as possible for me

**Comment by Durgesh-Vaigandla** [comment]
The issue was resolved earlier but didn't added to the main yet
