### ISSUE TITLE
Add back to top button.

### ISSUE THREAD

**Issue by maradadivyasree020** [CSEdgeOfficial/learn.csedge.courses#511]
### Description

To add a button on the webpage which ensures to go back to the top of the webpage.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Aradhyajha** [comment]
Hello @Durgesh-Vaigandla .. i want to work on that issue please assign this task to me..i will complete this as soon as possible for me

**Comment by Durgesh-Vaigandla** [comment]
@Aradhyajha Exists already
