### ISSUE TITLE
[Feature] Add Social Media Icons

### ISSUE THREAD

**Issue by Harshsaini001** [CSEdgeOfficial/learn.csedge.courses#513]
### Description

I want to add social media icons to your website, which will help people explore your connections.

### Screenshots

![Screenshot 2024-06-26 064821](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/127672737/b0b1a13f-fb26-468b-b5cf-7ca16b18305a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Harshsaini001** [comment]
Hey , I want to work on this feature request. Please assign this issue to me under GSSOC and also add GSSOC labels.

**Comment by Ankit389** [comment]
Hello Sir @CSEdgeOff please assign me this issue i want to work on it .. i will complete this as soon as possible for me
