### ISSUE TITLE
[Style] Cards UI-UX

### ISSUE THREAD

**Issue by AbheetHacker4278** [CSEdgeOfficial/learn.csedge.courses#515]
### What's the style idea?

The Card look is not great to attract the people , please assign this issue to me under gssoc 34 and i will make this Card more elegant and Eye appling to people .

### BEFORE
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/114290748/44ab0d5c-11a0-4843-8aed-e9c60b10be7f)

### AFTER

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/114290748/1666c5ec-17b4-4e90-81ca-97b57ef56cc6

@CSEdgeOff please assign to me under gssoc24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by AbheetHacker4278** [comment]
@Durgesh-Vaigandla please assign this issue to me under GSSOC24

**Comment by Ankit389** [comment]
Hello Sir @CSEdgeOff please assign me this issue i want to work on it .. i will complete this as soon as possible for me

**Comment by AbheetHacker4278** [comment]
@Ankit389 i am already working on it

**Comment by Durgesh-Vaigandla** [comment]
@AbheetHacker4278  It doesn't seem good actually, I mean it doesn't fit for the usecase
