### ISSUE TITLE
[Feature] Contact Us form and hover effect on social media icon

### ISSUE THREAD

**Issue by TBorundia** [CSEdgeOfficial/learn.csedge.courses#517]
### Description

Adding Contact Us form with the input fields.
Display of pop-up message after submission of form .
Giving hover effect to the social media icon similar to their logo color.
Form must have the UI matches to the theme of website.

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/168854094/4679e1e3-1c0a-477e-808f-10b7ac7e0bad

### Screenshots

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/168854094/5e6c27db-680c-452a-8de2-ab0054b3da5a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by TBorundia** [comment]
@CSEdgeOff , please assign this issue to me.

**Comment by Ankit389** [comment]
Hello Sir @CSEdgeOff please assign me this issue i want to work on it .. i will complete this as soon as possible for me

**Comment by Durgesh-Vaigandla** [comment]
@TBorundia The sample video was not good actually if you improve that you can work on it

**Comment by TBorundia** [comment]
> @TBorundia The sample video was not good actually if you improve that you can work on it

@Durgesh-Vaigandla 
Yes Sir, I shall try my best to match the form with the theme of website and improve it.
You can also suggest if any necessary changes are required.
I want to work on this issue, please assign it to me under GSSoC'24.

**Comment by TBorundia** [comment]
> > @TBorundia The sample video was not good actually if you improve that you can work on it
> 
> @Durgesh-Vaigandla Yes Sir, I shall try my best to match the form with the theme of website and improve it. You can also suggest if any necessary changes are required. I want to work on this issue, please assign it to me under GSSoC'24.

@Durgesh-Vaigandla Sir, is this issue assigned to me ?
Should I start working on it?
