### ISSUE TITLE
Styling/Adding footer in Blog page

### ISSUE THREAD

**Issue by rafiaatiq** [CSEdgeOfficial/learn.csedge.courses#52]
### What's the style idea?

The footer is not same as other page. I will add footer in blog page and style it.
Idea:
-We can opt for fonts, eg. pairing a sans-serif font for headings with a serif font for body text. we can also use font weights like semibold and light to create hierarchy.
-For modern look we align text to the left rather than centering.
-We can reduce the gap between icons in the footer to improve visual appeal. 
-We can move the "Follow Us" text closer to the icons for better visual alignment. 

I would like to work on this issue. Please assign this issue to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by iamrudhresh** [comment]
Assign this issue to me under GSSoc'24

**Comment by saswat733** [comment]
Assign this issue to me under GSSoc'24 would love to work on this !

**Comment by alishasingh06** [comment]
@CSEdgeOff please assign me this issue
