### ISSUE TITLE
[Feature]  Creating a fully working contact us page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [CSEdgeOfficial/learn.csedge.courses#520]
### Description

I will create a fully working contact page for the website where user can send his request or message to the owner just with a single click 

### Screenshots

![Screenshot 2024-06-27 214646](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/118350936/51a1b802-09d8-4430-b3eb-1969d36fb19f)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Ankit389** [comment]
Hello Sir @CSEdgeOff please assign me this issue i want to work on it .. i will complete this as soon as possible for me

**Comment by Durgesh-Vaigandla** [comment]
@Ayushmaanagarwal1211 No need of new page eventually in the pre existing one add the WhatsApp icon if you're interested as same as other icons

**Comment by Ayushmaanagarwal1211** [comment]
Yes actually i want to say that i will convert this page into working page like when user submit its details then it will Send directly to your email

**Comment by Durgesh-Vaigandla** [comment]
@Ayushmaanagarwal1211 Doesn't need actually you can just add the WhatsApp
