### ISSUE TITLE
Adding hovering effect to the nav bar contents

### ISSUE THREAD

**Issue by suhanigupta23** [CSEdgeOfficial/learn.csedge.courses#527]
### Description

Adding hovering effect to the nav bar contents which goes in sync to the nav bar and the website.

### Screenshots

<img width="1364" alt="Screenshot 2024-06-29 at 4 33 09 PM" src="https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/144280247/980500f6-ca48-4654-8898-1a1ece754a54">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Ansh101112** [comment]
@Durgesh-Vaigandla sir please assign me this issue
