### ISSUE TITLE
[Feature] Add social media icons to footer of page

### ISSUE THREAD

**Issue by IshaanXCoder** [CSEdgeOfficial/learn.csedge.courses#536]
### Description

<img width="1470" alt="image" src="https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/75419419/9c85ea86-a1a0-4a8e-af9f-ea1b5789c17e">

add social icons like in the below image

<img width="742" alt="image" src="https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/75419419/b7b39524-03d7-4d7f-8d08-2117c75c39fc">

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by IshaanXCoder** [comment]
@CSEdgeOff pls assign this issue to me

**Comment by Ansh101112** [comment]
@Durgesh-Vaigandla sir please assign this issue to me.
