### ISSUE TITLE
[Style] Enhancing the internship section in csedge.courses

### ISSUE THREAD

**Issue by ayush-848** [CSEdgeOfficial/learn.csedge.courses#54]
### What's the style idea?

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/126975547/495c885b-d0a0-477d-9eaf-b3e66ee71ee5)

The current internship section is not visually appealing.
**If it is assigned to me, I would change the _fonts, color, spacing, etc_ to make it look more appealing.**

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by ayush-848** [comment]
please assign this issue to me

**Comment by CSEdgeOff** [comment]
@ayush-848 Make it good you need to work on home.html file

**Comment by ayush-848** [comment]
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/126975547/921c4a88-d093-4b60-b984-eef6ccbc667a)

@CSEdgeOff where are the images? There is no folder in this repo.

**Comment by CSEdgeOff** [comment]
I have updated now fetch the repo again you'll find the folder csedge.courses work in it.

**Comment by ayush-848** [comment]
@CSEdgeOff Thank you, this made easier for me to navigate through the code

**Comment by CSEdgeOff** [comment]
@ayush-848 When i can expect your PR.

**Comment by ayush-848** [comment]
@CSEdgeOff I have done the styling and added a hover effect, but due to this the buttons are not working. So the styling is done, but now I am working on the integration

**Comment by ayush-848** [comment]
@CSEdgeOff I have requested a PR, please check

**Comment by mohitrajjha111** [comment]
@CSEdgeOff I see that @ayush-848 has done a great work and i have seen his changes in the code as well. 
Still I would like to try to Enhance the internship section again. 

I would like to try using bootstrap and css to enhance this section.

![send1](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125960660/b255c9ef-956e-4403-997a-26be5ca579cd)
![send2](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125960660/62b0d7c8-4e90-4599-b49c-3ba287c11e3b)
![send3](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125960660/fffa6413-c26d-4496-8bce-1629bc5fd779)

I tried working on it just to make sure that i am able to make it correct.
In it I will Use Bootstrap and css as mentioned.
In the above pics i have thought of a design...the image size i will adjust slightly to make it look much better..it is slightly oversized right now.

If i have your permission, Can i try my approach?
Please consider assigning it to me as well under GSSoC'24

**Comment by CSEdgeOff** [comment]
@mohitrajjha111 You need update your local repo frequently because new changes are applying to this repo frequently after fetching the new changes check the new changes and still want up enchace work on them.

**Comment by mohitrajjha111** [comment]
@CSEdgeOff I shall do the same. Please assign it to me as well.
