### ISSUE TITLE
Make cards look better on blog pages: style changes

### ISSUE THREAD

**Issue by shivnandk** [CSEdgeOfficial/learn.csedge.courses#540]
### What's the style idea?

We need to enhance the card effect by adding subtle shadow effects and interactive hovering effects. Shadows will provide depth to the cards, while hover effects will make the user interface more engaging and intuitive.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Ansh101112** [comment]
@Durgesh-Vaigandla sir please assign me this issue.
