### ISSUE TITLE
[Technical Writing] : Getting started with MERN

### ISSUE THREAD

**Issue by AMS003010** [CSEdgeOfficial/learn.csedge.courses#544]
### Description

I want to add an article about "Getting started with MERN"

This article  would have the following contents:
- What a Web Framework is?
- Configuring a MongoDB Atlas Cluster
- Building a API with Express.js
- Creating a React App
- Setting a Proxy from your Backend API server to the Frontend React App
- Styling and making Requests from the frontend

Outcomes:
- Will understand how to work with the MERN stack
- Will have made a full MERN application project from scratch
- Will be able to explore other node frameworks as well

### Screenshots

__No Response__

### Checklist

- [x] I have checked the existing issues.
- [x] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I am a GSSoC'24 contributor.
- [x] I want to work on this issue.

### Code of Conduct

- [x] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by vaishali-sharma-20** [comment]
Hello @AMS003010 and @CSEdgeOff , I want to work on this task. Can you please assign me this.
