### ISSUE TITLE
[Technical Writing] : E-commerce Webpage

### ISSUE THREAD

**Issue by Saipradyumnagoud** [CSEdgeOfficial/learn.csedge.courses#547]
### Description

How to Develop a E commerce Webpage

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff @Durgesh-Vaigandla please assign me the issue

**Comment by vaishali-sharma-20** [comment]
Hello @CSEdgeOff and @Durgesh-Vaigandla , I want to work on this Task. Can you please assign me this so I can contribute to this project.

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff  @Durgesh-Vaigandla please assign me the issue
