### ISSUE TITLE
[Feature] Adding a scroll to the top button

### ISSUE THREAD

**Issue by Rajul-29** [CSEdgeOfficial/learn.csedge.courses#549]
### Description

Provides a smooth scroll animation to the top
Button is fixed at the bottom right corner of the viewport

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Rajul-29** [comment]
Hey @Durgesh-Vaigandla!
Can you please assign me this issue under GSSOC'24
Thank you

**Comment by Ansh101112** [comment]
@Durgesh-Vaigandla please assign me this issue under gssoc'24
