### ISSUE TITLE
[Feature] Creating a Sticky Navbar

### ISSUE THREAD

**Issue by thevijayshankersharma** [CSEdgeOfficial/learn.csedge.courses#566]
### Description

Discover how a sticky navigation bar can improve user navigation on your website. By keeping key navigation links accessible as users scroll, this feature ensures seamless browsing experience without the need to manually scroll back to the top. Enhance usability and engagement by implementing a sticky navbar that remains fixed at the top of the page across different devices and screen sizes.

### Screenshots

Before:
![image](https://github.com/user-attachments/assets/aa3d1f0c-a242-44bf-82d5-6a56f3209840)

After:
![image](https://github.com/user-attachments/assets/e7984b24-802e-4957-ae70-8c184925a1e7)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Deepak2047** [comment]
I would like to work on this project .please assign to me.
