### ISSUE TITLE
I want to style your blog page and make it more appealing and attractive

### ISSUE THREAD

**Issue by komalgururanii** [CSEdgeOfficial/learn.csedge.courses#58]
### What's the style idea?

I want to align the items properly and add style to the search bar nav bar and categories i will make it look better and appealing. I would be grateful if you could consider assigning me this task. Please let me know if there are any specific requirements or guidelines I should follow.

Thank you for considering my request. I look forward to your response.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by asinha828** [comment]
hello, i would like to work on this issue. On my point of view the website looks so dull. i can make it better. i would really like to give my best in this contribution. can i please work on this

**Comment by CSEdgeOff** [comment]
@asinha828 Lot of people are working on the same things make your PR first or else work on another functionalities.
