### ISSUE TITLE
Add exciting hover effect on cards

### ISSUE THREAD

**Issue by Utsavladia** [CSEdgeOfficial/learn.csedge.courses#584]
### Description

the cards should be having a hover effect to make it look better

### Screenshots

![image](https://github.com/user-attachments/assets/ec44292e-15fb-458f-aad9-3d693d31e819)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Naveenkumar30838** [comment]
Assign this to me

**Comment by Utsavladia** [comment]
@Naveenkumar30838 
I already wanna work on it under GSSOC
kindly find other issues or create one
