### ISSUE TITLE
Reduce the sizes of card for better readability and add some hover effect

### ISSUE THREAD

**Issue by Utsavladia** [CSEdgeOfficial/learn.csedge.courses#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/48342b8e-9482-4438-9bc7-6c4e561a0e9b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by yashi301** [comment]
Please assign this task to me

**Comment by Utsavladia** [comment]
@yashi301 
They won't assign it seems... cuz its been many days i opened this issue..
better find some issue in other repositories
