### ISSUE TITLE
[Style] Footer section enhancements @learn.csedge.courses

### ISSUE THREAD

**Issue by rhythmnarang1** [CSEdgeOfficial/learn.csedge.courses#6]
There is not defined gap between contact us and follow us.

**Comment by rhythmnarang1** [comment]
Please assign this issue to me.

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by sahithinandikula** [comment]
I am interested in fixing the issue ,would hope that task will be assigned
