### ISSUE TITLE
[Feature] Making Application form visually good and connects to google sheets

### ISSUE THREAD

**Issue by CSEdgeOff** [CSEdgeOfficial/learn.csedge.courses#60]
### Description

We have a Application form for the internship application currently we're using google forms for that we're willing to enhance the user experience so create a google application form use our current application for reference and the data need to be store on the google sheet after filling 

I here that there is a possible way that we can design the Google form to look stunning.
https://csedge.courses Here is the application form

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by kairveeehh** [comment]
@CSEdgeOff would like to work on this issue as I am done with the previous , 
## please assign it  to me

**Comment by RickyParte** [comment]
@CSEdgeOff i like to work on it. 
** Please assign. **

**Comment by AmrutaJayanti** [comment]
@CSEdgeOff Can you assign this task to to me

**Comment by CSEdgeOff** [comment]
### Write your solutions here we'll pick the best approach of solution
7995665539

**Comment by AmrutaJayanti** [comment]
@CSEdgeOff Do we have to send our solution through Whatsapp

**Comment by CSEdgeOff** [comment]
@AmrutaJayanti Make a PR that explains well and add screenshots of the output if necessary add video also.

**Comment by CSEdgeOff** [comment]
@AvdhutPailwan We have a form already in the web click on the apply now button on the main domain.

**Comment by AvdhutPailwan** [comment]
> @AvdhutPailwan We have a form already in the web click on the apply now button on the main domain.

I have seen the form and the form can be made visually appealing and also the data submitted can be seen in google sheets but there are no fields in the form which the user will submit I was asking for that

**Comment by CSEdgeOff** [comment]
@AvdhutPailwan I think you might visited only one section in the 2nd section their are the fields present.

**Comment by AvdhutPailwan** [comment]
> @AvdhutPailwan I think you might visited only one section in the 2nd section their are the fields present.

Okay I'll check it out.

**Comment by AvdhutPailwan** [comment]
> > @AvdhutPailwan I think you might visited only one section in the 2nd section their are the fields present.
> 
> Okay I'll check it out.

@CSEdgeOff can provide the link please I can't seem to find it on the website

**Comment by RickyParte** [comment]
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/77445318/90cb63e7-fd4e-44a0-83be-806cddb1044d)
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/77445318/3ca20168-31af-43d2-bcd4-ce06053d2041)

See this I have done this if any style related changes needed....

![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/77445318/85230f20-8ef6-4176-bbd1-99f7f48769ea)

**Comment by drick-infinity** [comment]
As I learned MERN full stack development,I will create dynamic web pages  
![Screenshot (9)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/116994649/914ff176-724c-441f-9cc9-d23b3d1d035f)
![Screenshot (41)](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/116994649/6b085708-ccce-4636-8564-56b911747733)

I would like to create some cards or better ui of form section and navbar 


here are some design I would like to create a dynamic web page full 
assign this issue to me under gssoc'24

**Comment by Yuvraj960** [comment]
@Durgesh-Vaigandla Please assign this issue to me under GSSoC24. I will connect the form to the mongoDB
