### ISSUE TITLE
[Style] About section is not aligned

### ISSUE THREAD

**Issue by nisargaa20** [CSEdgeOfficial/learn.csedge.courses#61]
### What's the style idea?

We need to improve the contents appear more attractive by proper alignment 

Kindly assign me this issue under #gssoc'24.

![CSEdge Internship - Google Chrome 11-05-2024 12_54_16](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125184228/6ce4e29a-1b92-49ac-9a8d-8443c7c56e03)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by utkarsh2023021** [comment]
I would like to take on the task of resolving this alignment issue. With my experience, I am confident that I can rectify this issue promptly and ensure that the "About" section is properly aligned.

Could you please assign this task to me?

**Comment by CSEdgeOff** [comment]
#72 Work on total about section make is good looking and responsive in all views
