### ISSUE TITLE
[Style] Add contact us page

### ISSUE THREAD

**Issue by nisargaa20** [CSEdgeOfficial/learn.csedge.courses#62]
### What's the style idea?

We need to improve contacting admin not only through email . We can make contact us page so users can directly fill the form and submit their messages . I can work on front end .

Kindly assign me this issue under #gssoc'24.

![CSEdge Internship - Google Chrome 11-05-2024 12_51_44](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125184228/852769a9-f375-4d44-afc7-219ef3e33a56)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by ATHARV-YOGI** [comment]
can you assign me this issue ?

**Comment by CSEdgeOff** [comment]
@nisargaa20 Try doing both frontend and backend tell us the different approaches that you could solve that. text here 7995665539

**Comment by nisargaa20** [comment]
For frontend approach is in the picture (kindly ignore the color only look at the format )
backend we can use emailjs 
but first I will work on front end 

![hi](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125184228/ed30ea8d-158b-4f47-9f6a-fc4f13dcba67)

**Comment by atharvarekhawar** [comment]
hey @CSEdgeOff , I would like to work on this issue if no one is working on this, as there is no response from 3 weeks.

My approach -:
1.Let user fill the form and on submit the response is directed to your email via email.js.
2.The response is sent to backend and using nodemailer service it is send to your email id .

**Comment by nisargaa20** [comment]
@atharvarekhawar I have already raised an PR for the front end. You can raise a new issue for the back end functionality.

**Comment by nisargaa20** [comment]
@CSEdgeOff Hello , why there is no response for the PR kindly let me know

**Comment by CSEdgeOff** [comment]
> @CSEdgeOff Hello , why there is no response for the PR kindly let me know 

Mention the PR number

**Comment by nisargaa20** [comment]
@CSEdgeOff Contact us section #62
PR =  #370

**Comment by nisargaa20** [comment]
@CSEdgeOff You didnt merge it or convey whats wrong now it showed conflict I resolved and opened new PR. 
I checked others PR they are also facing conflict as u r not merging them since many weeks.

kindly let us all know why u r not merging

**Comment by atharvarekhawar** [comment]
hey @CSEdgeOff , you closed the PR related to this issue , I would like to contribute to this issue , please assign this to me.
