### ISSUE TITLE
[Style] Free content section

### ISSUE THREAD

**Issue by nisargaa20** [CSEdgeOfficial/learn.csedge.courses#63]
### What's the style idea?

We need to improve the look of the website . The blank at the middle of the books page is not attractive . We can add one more book content there so that it looks good.

Kindly assign me this issue under #gssoc'24.

![CSEdge Internship - Google Chrome 11-05-2024 12_51_28](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125184228/a6a2f6f0-40cc-41c7-a235-7fb7e490641a)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@nisargaa20 Work in the folder csedge.courses and the file name is Resources.html

**Comment by PriyanshuValiya** [comment]
I would like to work on this project. Please assign it to me.

**Comment by atharvarekhawar** [comment]
hey @CSEdgeOff , I would like to work on this issue , if no one is working on this , please assign this to me.
