### ISSUE TITLE
[Style] Hovering Effect 

### ISSUE THREAD

**Issue by Tejaswini-628** [CSEdgeOfficial/learn.csedge.courses#64]
### What's the style idea?

We need to improve the hovering effect  in the navbar on main page.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by Caliber-Ruchi** [comment]
I would like to work upon it. Kindly assign it.

**Comment by Tejaswini-628** [comment]
I cannot assign it to you, as I'm a contributor.And moreover I raised the issue to work up in it...

**Comment by CSEdgeOff** [comment]
#7 already raised the issue on navbar work on it
