### ISSUE TITLE
[Style] Improvement in the cards UI

### ISSUE THREAD

**Issue by triggereddown** [CSEdgeOfficial/learn.csedge.courses#66]
### What's the style idea?

We need to improve the UI of the website cards, as the page's UI  is more focused on the edge and box shapes i would like to try and improve the Internship cards and their respective buttons and try to provide a new look to it
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/137756305/8bb26e48-8150-4e02-8a45-1d307cdb4808)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by HardCoder404** [comment]
Please assign me this issue. I ll be glad to work on that.

**Comment by Manishar55** [comment]
Hello @CSEdgeOff 
I want to improve the cards styling, can you please assign this issue to me

**Comment by paridhi1509** [comment]
Hi @CSEdgeOff 
I would like to work on this issue under GSSoC'24
Please assign it to me

**Comment by vaishnavip27** [comment]
Hey @CSEdgeOff  I would love to work on this issue as a designer and a frontend developer. Please assign me this issue. Looking forward for your approval

**Comment by TheNikhilRaj** [comment]
Hii can you please assign the task to me.

**Comment by sakshi261203** [comment]
Hi Durgesh-Vaigandla , Please assign the task to me...
