### ISSUE TITLE
Fix Nav Bar

### ISSUE THREAD

**Issue by Aarushcpp** [CSEdgeOfficial/learn.csedge.courses#7]
I would like to fix the position of navigation bar on the page so that when user scrolls down it doesn't go from the top of the page.

**Comment by anshgautam-github** [comment]
can i work on this issue ?

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by negia7014** [comment]
could you assign this issue to me ??

**Comment by nidhaahmed** [comment]
Hello there!

I'm eager to jump in and help with fixing the navigation bar (#7). It seems like an interesting challenge, and I'm confident I can lend a hand in finding a solution.

Could you assign me this issue?
Looking forward to collaborating with you all on this!

Best regards,
Nidha Ahmed Mohammad.

**Comment by anirudh-why** [comment]
I have worked on lot of projects with the nav bar .I would like to handle this issue.
i'll imporove on the ui.

**Comment by sarthak-stranger** [comment]
Hi, Can you please assign this issue to me, i have so experience in designing so i can fix the navbar and also give the better UI and user experience to it according to the main theme.

**Comment by Sathya-reddy1658** [comment]
I've been working on header and footer sections of my recent projects , i can add micro interactions into footer and make it look more engaging , assign me this task

**Comment by yashbalpande** [comment]
please assign me this task

**Comment by sahithinandikula** [comment]
I am interested in fixing the navbar and make changes in it  .I am ready to take up the task

**Comment by Abdal192003** [comment]
Hi , could you please assign me this issue under gssoc'24 , will try my best to solve this issue.
Thanks

**Comment by Roshan1007** [comment]
Hi, I would like to work on this issue under GSSOC24. Could you assign this issue to me?

**Comment by Tanishka023** [comment]
Heyy!! Can you please assign this to me, I'm eager to contribute and would love working on this under GSSoC'24.
Thanks!

**Comment by Nih1tGupta** [comment]
I would like to fix the position of navigation bar on the page so that when user scrolls down it doesn't go from the top of the page

**Comment by SAURABHVERMA00** [comment]
I've noticed that the navbar could use some enhancements for a better user experience, and the position of the navbar isn't fixed. Could you please assign me to address this issue

**Comment by TheNikhilRaj** [comment]
Hii can you please assign the task to me.

**Comment by sanchitkhthpalia** [comment]
**hello, please assign this issue to me under GSSOC'24.**
