### ISSUE TITLE
To center the "GoToTop" arrowkey in About page.

### ISSUE THREAD

**Issue by HardCoder404** [CSEdgeOfficial/learn.csedge.courses#70]
### What's the style idea?

We need to improve the "GoToTop" button styling in about page. The arrow is not in the center.
Kindly see the issue and assign it to me. I ll be glad to work on that.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@HardCoder404 ok you need to work in the folder csedge.courses. Provide the Screenshots or video while making PR.

**Comment by HardCoder404** [comment]
I've generated a PR. Kindly review and merge it.

**Comment by HardCoder404** [comment]
## ScreenShot of the O/P : 
![Screenshot 2024-05-11 185429](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/127084297/8388529f-6d4c-48c6-8a17-7eaeda6f8a63)
