### ISSUE TITLE
[Style] CSEdge.courses About Section Enchancement

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [CSEdgeOfficial/learn.csedge.courses#72]
### What's the style idea?

We need to improve the Justification of the text Inside the Internships Section Cards and About Section and also the size of the text is also too large  under the about section .
I want to work on this under GSSOC if found suitable kindly assign this to me .
![Screenshot 2024-05-11 192220](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/118350936/2e30a710-38e7-4f12-a873-6be27fd2f9dd)
![Screenshot 2024-05-11 193412](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/118350936/13130954-fc6e-43fc-a72c-553f6217f6d3)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".
![Screenshot 2024-05-11 193401](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/118350936/8682341e-7701-4c13-9d31-8d1da7a42401)

**Comment by CSEdgeOff** [comment]
@Ayushmaanagarwal1211 Work on About section only make sure the views responsive in mobile/laptop/desktop

**Comment by Ayushmaanagarwal1211** [comment]
I want to work on that .

**Comment by Ayushmaanagarwal1211** [comment]
Ok i am working on that .

**Comment by PriyanshuValiya** [comment]
I would like to work on this project. Please assign it to me.

**Comment by GarimaSingh0109** [comment]
@CSEdgeOff I am willing to work on this issue. I have made a lot of websites with good UI UX. Kindly assign me this task.

**Comment by Ayushmaanagarwal1211** [comment]
Hii @CSEdgeOff I want to start work can you assign this to me
