### ISSUE TITLE
BUG: Grammatical error in the Internship card

### ISSUE THREAD

**Issue by Debarunn1806** [CSEdgeOfficial/learn.csedge.courses#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The internship card which have a coming soon label on them have a grammatical error where it is written as 'comming soon' instead of 'coming soon' .

![Screenshot 2024-05-11 192734](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/106834322/3d48d1e1-2d44-4830-8c2e-a7524b39cfd1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Debarunn1806** [comment]
Hello I am Debarun Chakrabortty and am contributing in this project under GSSOC'24 , Do assign me this issue as i can solve it in no time enhancing the UX of the website.

**Comment by CSEdgeOff** [comment]
@Debarunn1806 Go ahead make a PR On it we'll update to you if possible to merge

**Comment by vaishali-sharma-20** [comment]
Please assign this task to me. I would like to contribute in this project and I can fix this bug

**Comment by aminasaeed223** [comment]
I will be working on it.

**Comment by Debarunn1806** [comment]
Hey I have made a pull request please check it . Thankyou

**Comment by sadhvi1244** [comment]
Hello @CSEdgeOff 
I'd like to address the matter. Kindly assign this task to me for GSSOC'24.

**Comment by Deepanjal-Uppal** [comment]
Hey I have made a pull request please check it . 
Thankyou

**Comment by SuryanshuKushwaha** [comment]
@CSEdgeOff  please assign me this issue

**Comment by MadalapureVaishnavi** [comment]
@CSEdgeOff  can you assign me this issue

**Comment by HarshadaGirase** [comment]
Hello @CSEdgeOff .
I am GSSoC'24 Contributor.
Please assign this task to me.
