### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Stiffpixels** [CSEdgeOfficial/learn.csedge.courses#76]
### Description

A progress bar on top of the blogs' page that tracks how much of the blog has been read by the reader. Please assign this issue to me.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@Stiffpixels Work on this make the changes only in the posts folder.

**Comment by Stiffpixels** [comment]
> @Stiffpixels Work on this make the changes only in the posts folder.

just one question where should I write my JavaScript and CSS I would like to write in the script.js file and styles.css file in the posts folder if thats alright.

**Comment by CSEdgeOff** [comment]
@Stiffpixels yes you can

**Comment by Raghavi-22** [comment]
As a contributor ,I would like to work on this issue.Could you assign me this issue @CSEdgeOff
