### ISSUE TITLE
BUG: Navbar not fixed at the top

### ISSUE THREAD

**Issue by adarsh-fxz** [CSEdgeOfficial/learn.csedge.courses#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description:
Currently, the navbar is not fixed at the top of the page. This creates inconvenience as users have to scroll to the top whenever they wish to switch to another page.

Expected Behavior:
The navbar should be fixed at the top of the page, ensuring easy navigation regardless of the user's scroll position.

Steps to Reproduce:

Scroll down the page.
Attempt to switch to another page.
Notice that you have to scroll back to the top to access the navbar.

This issue affects user experience and navigation efficiency, especially on longer pages. Ensuring a fixed navbar would greatly enhance usability.

Proposed Solution:
Implement a fixed navbar that remains visible at the top of the page even when scrolling down.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CSEdgeOff** [comment]
This issue has already raised #7 work on that.
