### ISSUE TITLE
Add social media and feedback section in blog page[Feature] <write a small description here>

### ISSUE THREAD

**Issue by rajlaxmi03** [CSEdgeOfficial/learn.csedge.courses#78]
### Description

Add social media and feedback section in blog page

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@rajlaxmi03 Already #26 and #22 are raised the same issue
