### ISSUE TITLE
Adding FAQ section

### ISSUE THREAD

**Issue by rajlaxmi03** [CSEdgeOfficial/learn.csedge.courses#79]
### Description

Adding FAQ section 

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@rajlaxmi03 where will you add the FAQ section we have one already isn't it
