### ISSUE TITLE
Improve blog page of the website

### ISSUE THREAD

**Issue by Sneha123-zudo** [CSEdgeOfficial/learn.csedge.courses#8]
Please assign me this issue under GSSOC'24

**Comment by anirudh-why** [comment]
I'd like to work on this issue. Please assign me this under GSSOC'24

**Comment by nishant0708** [comment]
hey @Sneha123-zudo 
 can you assign me this issue

**Comment by Damini2004** [comment]
I can resolve this issue.Please assign me this issue.

I would like to contribute by making the following changes:

Responsiveness to whole blog page will be achieve.
Add carousel to the famous blog that make it more tempting.
Theme Changing mechanism as per the user required.
Card and hover effect for blogs.
Social Media Integration via which user can easily contact with the blog writer.
These above enhance contribute a alot for seeking more number of attention.
