### ISSUE TITLE
[Style] Enhance the Why CSEdge Internship section of the webiste

### ISSUE THREAD

**Issue by shnwz-solves** [CSEdgeOfficial/learn.csedge.courses#80]
### What's the style idea?

We need to improve the Why CSEdge Internship section of the website which will offer better UI to improve UX.
![Screenshot 2024-05-11 204523](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/126380641/a18d97a1-729a-494e-a4c2-80089826a5e3)

### Checklist

- [X] I have checked the existing issues.
- [x] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
Send me your PR after enhancements @shnwz-solves with screenshots

**Comment by shnwz-solves** [comment]
> Send me your PR after enhancements @shnwz-solves with screenshots

Okay @CSEdgeOff , I will send pr after enhancement, working on it.

**Comment by sadhvi1244** [comment]
Hello @CSEdgeOff 
I would like to work on the issue. Please assign this task ti me under GSSOC'24.

**Comment by Satuti99** [comment]
Hello sir @CSEdgeOff I would like to work on this issue. Please assign me this task.
