### ISSUE TITLE
[Style] Styling the nav bar

### ISSUE THREAD

**Issue by Manishar55** [CSEdgeOfficial/learn.csedge.courses#83]
### What's the style idea?

We need to improve the nav bar as it is looking very simple I would like to add some hover effects 
![Screenshot 2024-05-11 214529](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/154615478/62c5c068-9ca2-4a6e-8b16-c7e48dc58b64)
@CSEdgeOff  kindly assign this issue to me under gssoc24

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
This issue has been already raised #7 work on it
