### ISSUE TITLE
Footer UI improvement 

### ISSUE THREAD

**Issue by vignesh-0512** [CSEdgeOfficial/learn.csedge.courses#87]
### Description

I would like to make footer more attractive also I would like to add social media icons of your site can you please assign me this issue under gssoc'24 also provide the links of your social media to add in a site

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@vignesh-0512 Specify the Footer you're willing to work 
with screenshots

**Comment by vignesh-0512** [comment]
Here in the production site footer is very simple, so i would like to increase UI design and adding some link, newsletter and also we can add social media icons.
iam willing to work on this footer.
![Screenshot_20240511-225100~2](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/115525353/90e13ed9-9a15-4ac3-9da0-c75bb8bad50c)

**Comment by CSEdgeOff** [comment]
@vignesh-0512 Yup work on it but not necessary to add the newsletter.

**Comment by CSEdgeOff** [comment]
But work on the issue #6

**Comment by vignesh-0512** [comment]
can you please ssign this issue to me? also please add what features you are expecting to develop.
