### ISSUE TITLE
[Style] Using more color which are in the color palette of the logo of website

### ISSUE THREAD

**Issue by IshaSaini11** [CSEdgeOfficial/learn.csedge.courses#89]
### What's the style idea?

We need to improve the color palette of the website's pages to make it look more user friendly and color oriented which also represents the theme of the company/ website.

Please assign me this issue and also label this issue with GSSOC and it's level.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
@IshaSaini11 I'm assigning you under GSSoC'24 Work better.

**Comment by IshaSaini11** [comment]
Will be done. Thank you for assigning.

**Comment by IshaSaini11** [comment]
Respective mentor, I made a fork, then updated the changes, and then created a pull request too, but at last the button for merging the PR is not showing, what should I do further?

![query](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/87354071/d8f40445-78cb-4fa3-b09f-8bb1279862ba)

**Comment by paridhi1509** [comment]
Please assign me this issue as i would like to work on it under GSSoC'24
