### ISSUE TITLE
Position and Style of Search Bar, Categories sec and Recent Posts in a better way in Main page

### ISSUE THREAD

**Issue by Divyanshu832** [CSEdgeOfficial/learn.csedge.courses#90]
### What's the style idea?

We need to improve the style of elements on main page as we can take the search bar just below or on the nav bar and we can give the option to choose categories just below that which should be in a dropdown affect menu. Moreover We can add our "recent posts" just above footer. We can even design footer in better way with enhancing UI.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
