### ISSUE TITLE
[Feature] <Introducing toggle button for dark mode>

### ISSUE THREAD

**Issue by Divyanshu832** [CSEdgeOfficial/learn.csedge.courses#91]
### Description

We can add a toggle button right in the nav bar so that, user can switch between dark mode and light mode quite easily. It would enhance user's experience. And we have to use darker colors for dark mode.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by CSEdgeOff** [comment]
#19 Work on this issue work together.
