### ISSUE TITLE
Styling the header section

### ISSUE THREAD

**Issue by safael-alami** [CSEdgeOfficial/learn.csedge.courses#92]
### What's the style idea?

The project name should be positioned on the top left of the website, possibly with the same background as the footer for consistency in design.

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
