### ISSUE TITLE
Feat: Automate greeting using Github bot 🤖

### ISSUE THREAD

**Issue by dakshsinghrathore** [CSEdgeOfficial/learn.csedge.courses#93]
### Description

As the contributor count rises on the repo, it becomes increasingly challenging for maintainers to personally greet and encourage each contributor for their valuable input. Equally important is the reminder for them to review the project's contribution guidelines.

### PR greeting message ⬇️ 

![CleanShot_2024-05-11_at_14 39 402x](https://github.com/hereisSwapnil/ExamTime/assets/115932772/f39a24ed-dfd9-46c4-8b14-24281aa1711e)

### ISSUE greeting message ⬇️ 

![CleanShot_2024-05-11_at_14 40 482x](https://github.com/hereisSwapnil/ExamTime/assets/115932772/1b275744-94b8-4199-81f4-1ef42dfd84a8)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

**Comment by dakshsinghrathore** [comment]
@CSEdgeOff  I would like to work on this issue under GSSOC24, kindly assign me

**Comment by CSEdgeOff** [comment]
@dakshsinghrathore Submit your PR ASAP.

**Comment by dakshsinghrathore** [comment]
@CSEdgeOff Kindly review the PR and merge it.
