### ISSUE TITLE
BUG: Unable to open design using Provided link.

### ISSUE THREAD

**Issue by vaishali-sharma-20** [CSEdgeOfficial/learn.csedge.courses#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am unable to open Design using the Provided design Link. Can you please provide a design link?
Provided Link: https://link-to-design-resource/
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/89777420/76b038c2-fd8d-4049-aa5c-b48cec61abb3)

Showing error:
![image](https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/89777420/d7cec57d-d6cd-45f5-b95f-3bc11a39f3b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by CSEdgeOff** [comment]
@vaishali-sharma-20 the typo errors can't be consider into GSSoC
